#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArmsApi.Model.DataContext
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="ARMS")]
	public partial class ARMSDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region 拡張メソッドの定義
    partial void OnCreated();
    partial void InsertTnResinMixMat(TnResinMixMat instance);
    partial void UpdateTnResinMixMat(TnResinMixMat instance);
    partial void DeleteTnResinMixMat(TnResinMixMat instance);
    partial void InsertTnMaterials(TnMaterials instance);
    partial void UpdateTnMaterials(TnMaterials instance);
    partial void DeleteTnMaterials(TnMaterials instance);
    partial void InsertTmDieShearSampling(TmDieShearSampling instance);
    partial void UpdateTmDieShearSampling(TmDieShearSampling instance);
    partial void DeleteTmDieShearSampling(TmDieShearSampling instance);
    partial void InsertTmEmployee(TmEmployee instance);
    partial void UpdateTmEmployee(TmEmployee instance);
    partial void DeleteTmEmployee(TmEmployee instance);
    partial void InsertTnCarrierWorkData(TnCarrierWorkData instance);
    partial void UpdateTnCarrierWorkData(TnCarrierWorkData instance);
    partial void DeleteTnCarrierWorkData(TnCarrierWorkData instance);
    partial void InsertTmGeneral(TmGeneral instance);
    partial void UpdateTmGeneral(TmGeneral instance);
    partial void DeleteTmGeneral(TmGeneral instance);
    partial void InsertTnSubstrateInfo(TnSubstrateInfo instance);
    partial void UpdateTnSubstrateInfo(TnSubstrateInfo instance);
    partial void DeleteTnSubstrateInfo(TnSubstrateInfo instance);
    partial void InsertTmDenyCutBlendType(TmDenyCutBlendType instance);
    partial void UpdateTmDenyCutBlendType(TmDenyCutBlendType instance);
    partial void DeleteTmDenyCutBlendType(TmDenyCutBlendType instance);
    partial void InsertTmPSTeser(TmPSTeser instance);
    partial void UpdateTmPSTeser(TmPSTeser instance);
    partial void DeleteTmPSTeser(TmPSTeser instance);
    partial void InsertTnAGVPSTester(TnAGVPSTester instance);
    partial void UpdateTnAGVPSTester(TnAGVPSTester instance);
    partial void DeleteTnAGVPSTester(TnAGVPSTester instance);
    partial void InsertTmLineconfigSignalDisplay(TmLineconfigSignalDisplay instance);
    partial void UpdateTmLineconfigSignalDisplay(TmLineconfigSignalDisplay instance);
    partial void DeleteTmLineconfigSignalDisplay(TmLineconfigSignalDisplay instance);
    partial void InsertTnMoldDischargePressure(TnMoldDischargePressure instance);
    partial void UpdateTnMoldDischargePressure(TnMoldDischargePressure instance);
    partial void DeleteTnMoldDischargePressure(TnMoldDischargePressure instance);
    #endregion
		
		public ARMSDataContext() : 
				base(global::ArmsApi.Properties.Settings.Default.ARMSConnectionString2, mappingSource)
		{
			OnCreated();
		}
		
		public ARMSDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ARMSDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ARMSDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ARMSDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<TnResinMixMat> TnResinMixMat
		{
			get
			{
				return this.GetTable<TnResinMixMat>();
			}
		}
		
		public System.Data.Linq.Table<TnMaterials> TnMaterials
		{
			get
			{
				return this.GetTable<TnMaterials>();
			}
		}
		
		public System.Data.Linq.Table<TmDieShearSampling> TmDieShearSampling
		{
			get
			{
				return this.GetTable<TmDieShearSampling>();
			}
		}
		
		public System.Data.Linq.Table<TmEmployee> TmEmployee
		{
			get
			{
				return this.GetTable<TmEmployee>();
			}
		}
		
		public System.Data.Linq.Table<TnCarrierWorkData> TnCarrierWorkData
		{
			get
			{
				return this.GetTable<TnCarrierWorkData>();
			}
		}
		
		public System.Data.Linq.Table<TmGeneral> TmGeneral
		{
			get
			{
				return this.GetTable<TmGeneral>();
			}
		}
		
		public System.Data.Linq.Table<TnSubstrateInfo> TnSubstrateInfo
		{
			get
			{
				return this.GetTable<TnSubstrateInfo>();
			}
		}
		
		public System.Data.Linq.Table<TmDenyCutBlendType> TmDenyCutBlendType
		{
			get
			{
				return this.GetTable<TmDenyCutBlendType>();
			}
		}
		
		public System.Data.Linq.Table<TmPSTeser> TmPSTeser
		{
			get
			{
				return this.GetTable<TmPSTeser>();
			}
		}
		
		public System.Data.Linq.Table<TnAGVPSTester> TnAGVPSTester
		{
			get
			{
				return this.GetTable<TnAGVPSTester>();
			}
		}
		
		public System.Data.Linq.Table<TmLineconfigSignalDisplay> TmLineconfigSignalDisplay
		{
			get
			{
				return this.GetTable<TmLineconfigSignalDisplay>();
			}
		}
		
		public System.Data.Linq.Table<TnMoldDischargePressure> TnMoldDischargePressure
		{
			get
			{
				return this.GetTable<TnMoldDischargePressure>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TnResinMixMat")]
	public partial class TnResinMixMat : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _mixresultid;
		
		private string _materialcd;
		
		private string _lotno;
		
    #region 拡張メソッドの定義
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmixresultidChanging(string value);
    partial void OnmixresultidChanged();
    partial void OnmaterialcdChanging(string value);
    partial void OnmaterialcdChanged();
    partial void OnlotnoChanging(string value);
    partial void OnlotnoChanged();
    #endregion
		
		public TnResinMixMat()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mixresultid", DbType= "NVarChar(50) NOT NULL", IsPrimaryKey=true)]
		public string mixresultid
		{
			get
			{
				return this._mixresultid;
			}
			set
			{
				if ((this._mixresultid != value))
				{
					this.OnmixresultidChanging(value);
					this.SendPropertyChanging();
					this._mixresultid = value;
					this.SendPropertyChanged("mixresultid");
					this.OnmixresultidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_materialcd", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string materialcd
		{
			get
			{
				return this._materialcd;
			}
			set
			{
				if ((this._materialcd != value))
				{
					this.OnmaterialcdChanging(value);
					this.SendPropertyChanging();
					this._materialcd = value;
					this.SendPropertyChanged("materialcd");
					this.OnmaterialcdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lotno", DbType="NVarChar(100) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string lotno
		{
			get
			{
				return this._lotno;
			}
			set
			{
				if ((this._lotno != value))
				{
					this.OnlotnoChanging(value);
					this.SendPropertyChanging();
					this._lotno = value;
					this.SendPropertyChanged("lotno");
					this.OnlotnoChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TnMaterials")]
	public partial class TnMaterials : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _materialcd;
		
		private string _lotno;
		
		private string _materialnm;
		
		private System.Nullable<System.DateTime> _limitdt;
		
		private int _isrestrict;
		
		private string _hmgroup;
		
		private int _delfg;
		
		private string _blendcd;
		
		private string _bincd;
		
		private System.Nullable<int> _isframe;
		
		private System.Nullable<int> _iswafer;
		
		private System.Nullable<int> _issampled;
		
		private System.DateTime _lastupddt;
		
		private string _workcd;
		
		private int _isbadmarkframe;
		
		private string _framemoldednm;
		
		private string _framemoldedclass;
		
		private string _framemoldeddt;
		
		private System.Nullable<int> _rankid;
		
		private string _supplyId;
		
		private string _dicewaferkb;
		
		private System.Nullable<float> _thicknessave;
		
		private string _ringid;
		
    #region 拡張メソッドの定義
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaterialcdChanging(string value);
    partial void OnmaterialcdChanged();
    partial void OnlotnoChanging(string value);
    partial void OnlotnoChanged();
    partial void OnmaterialnmChanging(string value);
    partial void OnmaterialnmChanged();
    partial void OnlimitdtChanging(System.Nullable<System.DateTime> value);
    partial void OnlimitdtChanged();
    partial void OnisrestrictChanging(int value);
    partial void OnisrestrictChanged();
    partial void OnhmgroupChanging(string value);
    partial void OnhmgroupChanged();
    partial void OndelfgChanging(int value);
    partial void OndelfgChanged();
    partial void OnblendcdChanging(string value);
    partial void OnblendcdChanged();
    partial void OnbincdChanging(string value);
    partial void OnbincdChanged();
    partial void OnisframeChanging(System.Nullable<int> value);
    partial void OnisframeChanged();
    partial void OniswaferChanging(System.Nullable<int> value);
    partial void OniswaferChanged();
    partial void OnissampledChanging(System.Nullable<int> value);
    partial void OnissampledChanged();
    partial void OnlastupddtChanging(System.DateTime value);
    partial void OnlastupddtChanged();
    partial void OnworkcdChanging(string value);
    partial void OnworkcdChanged();
    partial void OnisbadmarkframeChanging(int value);
    partial void OnisbadmarkframeChanged();
    partial void OnframemoldednmChanging(string value);
    partial void OnframemoldednmChanged();
    partial void OnframemoldedclassChanging(string value);
    partial void OnframemoldedclassChanged();
    partial void OnframemoldeddtChanging(string value);
    partial void OnframemoldeddtChanged();
    partial void OnrankidChanging(System.Nullable<int> value);
    partial void OnrankidChanged();
    partial void OnsupplyIdChanging(string value);
    partial void OnsupplyIdChanged();
    partial void OndicewaferkbChanging(string value);
    partial void OndicewaferkbChanged();
    partial void OnthicknessaveChanging(System.Nullable<float> value);
    partial void OnthicknessaveChanged();
    partial void OnringidChanging(string value);
    partial void OnringidChanged();
    #endregion
		
		public TnMaterials()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_materialcd", DbType="NVarChar(24) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string materialcd
		{
			get
			{
				return this._materialcd;
			}
			set
			{
				if ((this._materialcd != value))
				{
					this.OnmaterialcdChanging(value);
					this.SendPropertyChanging();
					this._materialcd = value;
					this.SendPropertyChanged("materialcd");
					this.OnmaterialcdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lotno", DbType="NVarChar(64) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string lotno
		{
			get
			{
				return this._lotno;
			}
			set
			{
				if ((this._lotno != value))
				{
					this.OnlotnoChanging(value);
					this.SendPropertyChanging();
					this._lotno = value;
					this.SendPropertyChanged("lotno");
					this.OnlotnoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_materialnm", DbType="NVarChar(32)")]
		public string materialnm
		{
			get
			{
				return this._materialnm;
			}
			set
			{
				if ((this._materialnm != value))
				{
					this.OnmaterialnmChanging(value);
					this.SendPropertyChanging();
					this._materialnm = value;
					this.SendPropertyChanged("materialnm");
					this.OnmaterialnmChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_limitdt", DbType="DateTime")]
		public System.Nullable<System.DateTime> limitdt
		{
			get
			{
				return this._limitdt;
			}
			set
			{
				if ((this._limitdt != value))
				{
					this.OnlimitdtChanging(value);
					this.SendPropertyChanging();
					this._limitdt = value;
					this.SendPropertyChanged("limitdt");
					this.OnlimitdtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_isrestrict", DbType="Int NOT NULL")]
		public int isrestrict
		{
			get
			{
				return this._isrestrict;
			}
			set
			{
				if ((this._isrestrict != value))
				{
					this.OnisrestrictChanging(value);
					this.SendPropertyChanging();
					this._isrestrict = value;
					this.SendPropertyChanged("isrestrict");
					this.OnisrestrictChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hmgroup", DbType="NVarChar(32)")]
		public string hmgroup
		{
			get
			{
				return this._hmgroup;
			}
			set
			{
				if ((this._hmgroup != value))
				{
					this.OnhmgroupChanging(value);
					this.SendPropertyChanging();
					this._hmgroup = value;
					this.SendPropertyChanged("hmgroup");
					this.OnhmgroupChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_delfg", DbType="Int NOT NULL")]
		public int delfg
		{
			get
			{
				return this._delfg;
			}
			set
			{
				if ((this._delfg != value))
				{
					this.OndelfgChanging(value);
					this.SendPropertyChanging();
					this._delfg = value;
					this.SendPropertyChanged("delfg");
					this.OndelfgChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_blendcd", DbType="NVarChar(50)")]
		public string blendcd
		{
			get
			{
				return this._blendcd;
			}
			set
			{
				if ((this._blendcd != value))
				{
					this.OnblendcdChanging(value);
					this.SendPropertyChanging();
					this._blendcd = value;
					this.SendPropertyChanged("blendcd");
					this.OnblendcdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bincd", DbType="NVarChar(8)")]
		public string bincd
		{
			get
			{
				return this._bincd;
			}
			set
			{
				if ((this._bincd != value))
				{
					this.OnbincdChanging(value);
					this.SendPropertyChanging();
					this._bincd = value;
					this.SendPropertyChanged("bincd");
					this.OnbincdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_isframe", DbType="Int")]
		public System.Nullable<int> isframe
		{
			get
			{
				return this._isframe;
			}
			set
			{
				if ((this._isframe != value))
				{
					this.OnisframeChanging(value);
					this.SendPropertyChanging();
					this._isframe = value;
					this.SendPropertyChanged("isframe");
					this.OnisframeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_iswafer", DbType="Int")]
		public System.Nullable<int> iswafer
		{
			get
			{
				return this._iswafer;
			}
			set
			{
				if ((this._iswafer != value))
				{
					this.OniswaferChanging(value);
					this.SendPropertyChanging();
					this._iswafer = value;
					this.SendPropertyChanged("iswafer");
					this.OniswaferChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_issampled", DbType="Int")]
		public System.Nullable<int> issampled
		{
			get
			{
				return this._issampled;
			}
			set
			{
				if ((this._issampled != value))
				{
					this.OnissampledChanging(value);
					this.SendPropertyChanging();
					this._issampled = value;
					this.SendPropertyChanged("issampled");
					this.OnissampledChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lastupddt", DbType="DateTime NOT NULL")]
		public System.DateTime lastupddt
		{
			get
			{
				return this._lastupddt;
			}
			set
			{
				if ((this._lastupddt != value))
				{
					this.OnlastupddtChanging(value);
					this.SendPropertyChanging();
					this._lastupddt = value;
					this.SendPropertyChanged("lastupddt");
					this.OnlastupddtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_workcd", DbType="NVarChar(10)")]
		public string workcd
		{
			get
			{
				return this._workcd;
			}
			set
			{
				if ((this._workcd != value))
				{
					this.OnworkcdChanging(value);
					this.SendPropertyChanging();
					this._workcd = value;
					this.SendPropertyChanged("workcd");
					this.OnworkcdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_isbadmarkframe", DbType="Int NOT NULL")]
		public int isbadmarkframe
		{
			get
			{
				return this._isbadmarkframe;
			}
			set
			{
				if ((this._isbadmarkframe != value))
				{
					this.OnisbadmarkframeChanging(value);
					this.SendPropertyChanging();
					this._isbadmarkframe = value;
					this.SendPropertyChanged("isbadmarkframe");
					this.OnisbadmarkframeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_framemoldednm", DbType="NVarChar(50)")]
		public string framemoldednm
		{
			get
			{
				return this._framemoldednm;
			}
			set
			{
				if ((this._framemoldednm != value))
				{
					this.OnframemoldednmChanging(value);
					this.SendPropertyChanging();
					this._framemoldednm = value;
					this.SendPropertyChanged("framemoldednm");
					this.OnframemoldednmChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_framemoldedclass", DbType="NVarChar(50)")]
		public string framemoldedclass
		{
			get
			{
				return this._framemoldedclass;
			}
			set
			{
				if ((this._framemoldedclass != value))
				{
					this.OnframemoldedclassChanging(value);
					this.SendPropertyChanging();
					this._framemoldedclass = value;
					this.SendPropertyChanged("framemoldedclass");
					this.OnframemoldedclassChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_framemoldeddt", DbType="NVarChar(550)")]
		public string framemoldeddt
		{
			get
			{
				return this._framemoldeddt;
			}
			set
			{
				if ((this._framemoldeddt != value))
				{
					this.OnframemoldeddtChanging(value);
					this.SendPropertyChanging();
					this._framemoldeddt = value;
					this.SendPropertyChanged("framemoldeddt");
					this.OnframemoldeddtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rankid", DbType="Int")]
		public System.Nullable<int> rankid
		{
			get
			{
				return this._rankid;
			}
			set
			{
				if ((this._rankid != value))
				{
					this.OnrankidChanging(value);
					this.SendPropertyChanging();
					this._rankid = value;
					this.SendPropertyChanged("rankid");
					this.OnrankidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_supplyId", DbType="NVarChar(50)")]
		public string supplyId
		{
			get
			{
				return this._supplyId;
			}
			set
			{
				if ((this._supplyId != value))
				{
					this.OnsupplyIdChanging(value);
					this.SendPropertyChanging();
					this._supplyId = value;
					this.SendPropertyChanged("supplyId");
					this.OnsupplyIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dicewaferkb", DbType="NVarChar(50)")]
		public string dicewaferkb
		{
			get
			{
				return this._dicewaferkb;
			}
			set
			{
				if ((this._dicewaferkb != value))
				{
					this.OndicewaferkbChanging(value);
					this.SendPropertyChanging();
					this._dicewaferkb = value;
					this.SendPropertyChanged("dicewaferkb");
					this.OndicewaferkbChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_thicknessave", DbType="Real")]
		public System.Nullable<float> thicknessave
		{
			get
			{
				return this._thicknessave;
			}
			set
			{
				if ((this._thicknessave != value))
				{
					this.OnthicknessaveChanging(value);
					this.SendPropertyChanging();
					this._thicknessave = value;
					this.SendPropertyChanged("thicknessave");
					this.OnthicknessaveChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ringid", DbType="NVarChar(24)")]
		public string ringid
		{
			get
			{
				return this._ringid;
			}
			set
			{
				if ((this._ringid != value))
				{
					this.OnringidChanging(value);
					this.SendPropertyChanging();
					this._ringid = value;
					this.SendPropertyChanged("ringid");
					this.OnringidChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TmDieShearSampling")]
	public partial class TmDieShearSampling : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _typecd;
		
		private string _judgeworkcd;
		
		private int _delfg;
		
		private string _updusercd;
		
		private System.DateTime _lastupddt;
		
    #region 拡張メソッドの定義
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OntypecdChanging(string value);
    partial void OntypecdChanged();
    partial void OnjudgeworkcdChanging(string value);
    partial void OnjudgeworkcdChanged();
    partial void OndelfgChanging(int value);
    partial void OndelfgChanged();
    partial void OnupdusercdChanging(string value);
    partial void OnupdusercdChanged();
    partial void OnlastupddtChanging(System.DateTime value);
    partial void OnlastupddtChanged();
    #endregion
		
		public TmDieShearSampling()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_typecd", DbType="NVarChar(24) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string typecd
		{
			get
			{
				return this._typecd;
			}
			set
			{
				if ((this._typecd != value))
				{
					this.OntypecdChanging(value);
					this.SendPropertyChanging();
					this._typecd = value;
					this.SendPropertyChanged("typecd");
					this.OntypecdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_judgeworkcd", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string judgeworkcd
		{
			get
			{
				return this._judgeworkcd;
			}
			set
			{
				if ((this._judgeworkcd != value))
				{
					this.OnjudgeworkcdChanging(value);
					this.SendPropertyChanging();
					this._judgeworkcd = value;
					this.SendPropertyChanged("judgeworkcd");
					this.OnjudgeworkcdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_delfg", DbType="Int NOT NULL")]
		public int delfg
		{
			get
			{
				return this._delfg;
			}
			set
			{
				if ((this._delfg != value))
				{
					this.OndelfgChanging(value);
					this.SendPropertyChanging();
					this._delfg = value;
					this.SendPropertyChanged("delfg");
					this.OndelfgChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_updusercd", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string updusercd
		{
			get
			{
				return this._updusercd;
			}
			set
			{
				if ((this._updusercd != value))
				{
					this.OnupdusercdChanging(value);
					this.SendPropertyChanging();
					this._updusercd = value;
					this.SendPropertyChanged("updusercd");
					this.OnupdusercdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lastupddt", DbType="DateTime NOT NULL")]
		public System.DateTime lastupddt
		{
			get
			{
				return this._lastupddt;
			}
			set
			{
				if ((this._lastupddt != value))
				{
					this.OnlastupddtChanging(value);
					this.SendPropertyChanging();
					this._lastupddt = value;
					this.SendPropertyChanged("lastupddt");
					this.OnlastupddtChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TmEmployee")]
	public partial class TmEmployee : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _empcode;
		
		private string _empname;
		
		private System.DateTime _lastupddt;
		
    #region 拡張メソッドの定義
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnempcodeChanging(int value);
    partial void OnempcodeChanged();
    partial void OnempnameChanging(string value);
    partial void OnempnameChanged();
    partial void OnlastupddtChanging(System.DateTime value);
    partial void OnlastupddtChanged();
    #endregion
		
		public TmEmployee()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_empcode", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int empcode
		{
			get
			{
				return this._empcode;
			}
			set
			{
				if ((this._empcode != value))
				{
					this.OnempcodeChanging(value);
					this.SendPropertyChanging();
					this._empcode = value;
					this.SendPropertyChanged("empcode");
					this.OnempcodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_empname", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string empname
		{
			get
			{
				return this._empname;
			}
			set
			{
				if ((this._empname != value))
				{
					this.OnempnameChanging(value);
					this.SendPropertyChanging();
					this._empname = value;
					this.SendPropertyChanged("empname");
					this.OnempnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lastupddt", DbType="DateTime NOT NULL")]
		public System.DateTime lastupddt
		{
			get
			{
				return this._lastupddt;
			}
			set
			{
				if ((this._lastupddt != value))
				{
					this.OnlastupddtChanging(value);
					this.SendPropertyChanging();
					this._lastupddt = value;
					this.SendPropertyChanged("lastupddt");
					this.OnlastupddtChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TnCarrierWorkData")]
	public partial class TnCarrierWorkData : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _carrierno;
		
		private string _lotno;
		
		private long _procno;
		
		private string _infoid;
		
		private string _value;
		
		private int _delfg;
		
		private System.DateTime _lastupddt;
		
    #region 拡張メソッドの定義
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OncarriernoChanging(string value);
    partial void OncarriernoChanged();
    partial void OnlotnoChanging(string value);
    partial void OnlotnoChanged();
    partial void OnprocnoChanging(long value);
    partial void OnprocnoChanged();
    partial void OninfoidChanging(string value);
    partial void OninfoidChanged();
    partial void OnvalueChanging(string value);
    partial void OnvalueChanged();
    partial void OndelfgChanging(int value);
    partial void OndelfgChanged();
    partial void OnlastupddtChanging(System.DateTime value);
    partial void OnlastupddtChanged();
    #endregion
		
		public TnCarrierWorkData()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_carrierno", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string carrierno
		{
			get
			{
				return this._carrierno;
			}
			set
			{
				if ((this._carrierno != value))
				{
					this.OncarriernoChanging(value);
					this.SendPropertyChanging();
					this._carrierno = value;
					this.SendPropertyChanged("carrierno");
					this.OncarriernoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lotno", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string lotno
		{
			get
			{
				return this._lotno;
			}
			set
			{
				if ((this._lotno != value))
				{
					this.OnlotnoChanging(value);
					this.SendPropertyChanging();
					this._lotno = value;
					this.SendPropertyChanged("lotno");
					this.OnlotnoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_procno", DbType="BigInt NOT NULL", IsPrimaryKey=true)]
		public long procno
		{
			get
			{
				return this._procno;
			}
			set
			{
				if ((this._procno != value))
				{
					this.OnprocnoChanging(value);
					this.SendPropertyChanging();
					this._procno = value;
					this.SendPropertyChanged("procno");
					this.OnprocnoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_infoid", DbType="NVarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string infoid
		{
			get
			{
				return this._infoid;
			}
			set
			{
				if ((this._infoid != value))
				{
					this.OninfoidChanging(value);
					this.SendPropertyChanging();
					this._infoid = value;
					this.SendPropertyChanged("infoid");
					this.OninfoidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_value", DbType="NVarChar(300) NOT NULL", CanBeNull=false)]
		public string value
		{
			get
			{
				return this._value;
			}
			set
			{
				if ((this._value != value))
				{
					this.OnvalueChanging(value);
					this.SendPropertyChanging();
					this._value = value;
					this.SendPropertyChanged("value");
					this.OnvalueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_delfg", DbType="Int NOT NULL")]
		public int delfg
		{
			get
			{
				return this._delfg;
			}
			set
			{
				if ((this._delfg != value))
				{
					this.OndelfgChanging(value);
					this.SendPropertyChanging();
					this._delfg = value;
					this.SendPropertyChanged("delfg");
					this.OndelfgChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lastupddt", DbType="DateTime NOT NULL")]
		public System.DateTime lastupddt
		{
			get
			{
				return this._lastupddt;
			}
			set
			{
				if ((this._lastupddt != value))
				{
					this.OnlastupddtChanging(value);
					this.SendPropertyChanging();
					this._lastupddt = value;
					this.SendPropertyChanged("lastupddt");
					this.OnlastupddtChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TmGeneral")]
	public partial class TmGeneral : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _tid;
		
		private string _code;
		
		private string _val;
		
		private string _val2;
		
		private int _delfg;
		
		private System.DateTime _updatedt;
		
		private string _updusercd;
		
    #region 拡張メソッドの定義
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OntidChanging(string value);
    partial void OntidChanged();
    partial void OncodeChanging(string value);
    partial void OncodeChanged();
    partial void OnvalChanging(string value);
    partial void OnvalChanged();
    partial void Onval2Changing(string value);
    partial void Onval2Changed();
    partial void OndelfgChanging(int value);
    partial void OndelfgChanged();
    partial void OnupdatedtChanging(System.DateTime value);
    partial void OnupdatedtChanged();
    partial void OnupdusercdChanging(string value);
    partial void OnupdusercdChanged();
    #endregion
		
		public TmGeneral()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tid", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string tid
		{
			get
			{
				return this._tid;
			}
			set
			{
				if ((this._tid != value))
				{
					this.OntidChanging(value);
					this.SendPropertyChanging();
					this._tid = value;
					this.SendPropertyChanged("tid");
					this.OntidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_code", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string code
		{
			get
			{
				return this._code;
			}
			set
			{
				if ((this._code != value))
				{
					this.OncodeChanging(value);
					this.SendPropertyChanging();
					this._code = value;
					this.SendPropertyChanged("code");
					this.OncodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_val", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string val
		{
			get
			{
				return this._val;
			}
			set
			{
				if ((this._val != value))
				{
					this.OnvalChanging(value);
					this.SendPropertyChanging();
					this._val = value;
					this.SendPropertyChanged("val");
					this.OnvalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_val2", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string val2
		{
			get
			{
				return this._val2;
			}
			set
			{
				if ((this._val2 != value))
				{
					this.Onval2Changing(value);
					this.SendPropertyChanging();
					this._val2 = value;
					this.SendPropertyChanged("val2");
					this.Onval2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_delfg", DbType="Int NOT NULL")]
		public int delfg
		{
			get
			{
				return this._delfg;
			}
			set
			{
				if ((this._delfg != value))
				{
					this.OndelfgChanging(value);
					this.SendPropertyChanging();
					this._delfg = value;
					this.SendPropertyChanged("delfg");
					this.OndelfgChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_updatedt", DbType="DateTime NOT NULL")]
		public System.DateTime updatedt
		{
			get
			{
				return this._updatedt;
			}
			set
			{
				if ((this._updatedt != value))
				{
					this.OnupdatedtChanging(value);
					this.SendPropertyChanging();
					this._updatedt = value;
					this.SendPropertyChanged("updatedt");
					this.OnupdatedtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_updusercd", DbType="NVarChar(50)")]
		public string updusercd
		{
			get
			{
				return this._updusercd;
			}
			set
			{
				if ((this._updusercd != value))
				{
					this.OnupdusercdChanging(value);
					this.SendPropertyChanging();
					this._updusercd = value;
					this.SendPropertyChanged("updusercd");
					this.OnupdusercdChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TnSubstrateInfo")]
	public partial class TnSubstrateInfo : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _datamatrix;
		
		private string _thicknessrank;
		
		private string _markingno;
		
		private string _mappingdata;
		
		private string _updusercd;
		
		private System.DateTime _lastupddt;
		
    #region 拡張メソッドの定義
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OndatamatrixChanging(string value);
    partial void OndatamatrixChanged();
    partial void OnthicknessrankChanging(string value);
    partial void OnthicknessrankChanged();
    partial void OnmarkingnoChanging(string value);
    partial void OnmarkingnoChanged();
    partial void OnmappingdataChanging(string value);
    partial void OnmappingdataChanged();
    partial void OnupdusercdChanging(string value);
    partial void OnupdusercdChanged();
    partial void OnlastupddtChanging(System.DateTime value);
    partial void OnlastupddtChanged();
    #endregion
		
		public TnSubstrateInfo()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_datamatrix", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string datamatrix
		{
			get
			{
				return this._datamatrix;
			}
			set
			{
				if ((this._datamatrix != value))
				{
					this.OndatamatrixChanging(value);
					this.SendPropertyChanging();
					this._datamatrix = value;
					this.SendPropertyChanged("datamatrix");
					this.OndatamatrixChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_thicknessrank", DbType="NVarChar(50)")]
		public string thicknessrank
		{
			get
			{
				return this._thicknessrank;
			}
			set
			{
				if ((this._thicknessrank != value))
				{
					this.OnthicknessrankChanging(value);
					this.SendPropertyChanging();
					this._thicknessrank = value;
					this.SendPropertyChanged("thicknessrank");
					this.OnthicknessrankChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_markingno", DbType="NVarChar(50)")]
		public string markingno
		{
			get
			{
				return this._markingno;
			}
			set
			{
				if ((this._markingno != value))
				{
					this.OnmarkingnoChanging(value);
					this.SendPropertyChanging();
					this._markingno = value;
					this.SendPropertyChanged("markingno");
					this.OnmarkingnoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mappingdata", DbType="NVarChar(MAX)")]
		public string mappingdata
		{
			get
			{
				return this._mappingdata;
			}
			set
			{
				if ((this._mappingdata != value))
				{
					this.OnmappingdataChanging(value);
					this.SendPropertyChanging();
					this._mappingdata = value;
					this.SendPropertyChanged("mappingdata");
					this.OnmappingdataChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_updusercd", DbType="NVarChar(50)")]
		public string updusercd
		{
			get
			{
				return this._updusercd;
			}
			set
			{
				if ((this._updusercd != value))
				{
					this.OnupdusercdChanging(value);
					this.SendPropertyChanging();
					this._updusercd = value;
					this.SendPropertyChanged("updusercd");
					this.OnupdusercdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lastupddt", DbType="DateTime NOT NULL")]
		public System.DateTime lastupddt
		{
			get
			{
				return this._lastupddt;
			}
			set
			{
				if ((this._lastupddt != value))
				{
					this.OnlastupddtChanging(value);
					this.SendPropertyChanging();
					this._lastupddt = value;
					this.SendPropertyChanged("lastupddt");
					this.OnlastupddtChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TmDenyCutBlendType")]
	public partial class TmDenyCutBlendType : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _typecd;
		
		private bool _delfg;
		
		private string _updusercd;
		
		private System.DateTime _lastupddt;
		
    #region 拡張メソッドの定義
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OntypecdChanging(string value);
    partial void OntypecdChanged();
    partial void OndelfgChanging(bool value);
    partial void OndelfgChanged();
    partial void OnupdusercdChanging(string value);
    partial void OnupdusercdChanged();
    partial void OnlastupddtChanging(System.DateTime value);
    partial void OnlastupddtChanged();
    #endregion
		
		public TmDenyCutBlendType()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_typecd", DbType="NVarChar(24) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string typecd
		{
			get
			{
				return this._typecd;
			}
			set
			{
				if ((this._typecd != value))
				{
					this.OntypecdChanging(value);
					this.SendPropertyChanging();
					this._typecd = value;
					this.SendPropertyChanged("typecd");
					this.OntypecdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_delfg", DbType="Bit NOT NULL")]
		public bool delfg
		{
			get
			{
				return this._delfg;
			}
			set
			{
				if ((this._delfg != value))
				{
					this.OndelfgChanging(value);
					this.SendPropertyChanging();
					this._delfg = value;
					this.SendPropertyChanged("delfg");
					this.OndelfgChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_updusercd", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string updusercd
		{
			get
			{
				return this._updusercd;
			}
			set
			{
				if ((this._updusercd != value))
				{
					this.OnupdusercdChanging(value);
					this.SendPropertyChanging();
					this._updusercd = value;
					this.SendPropertyChanged("updusercd");
					this.OnupdusercdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lastupddt", DbType="DateTime NOT NULL")]
		public System.DateTime lastupddt
		{
			get
			{
				return this._lastupddt;
			}
			set
			{
				if ((this._lastupddt != value))
				{
					this.OnlastupddtChanging(value);
					this.SendPropertyChanging();
					this._lastupddt = value;
					this.SendPropertyChanged("lastupddt");
					this.OnlastupddtChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TmPSTeser")]
	public partial class TmPSTeser : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _plantcd;
		
		private decimal _settingtime;
		
		private int _delfg;
		
		private System.DateTime _lastupddt;
		
    #region 拡張メソッドの定義
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnplantcdChanging(string value);
    partial void OnplantcdChanged();
    partial void OnsettingtimeChanging(decimal value);
    partial void OnsettingtimeChanged();
    partial void OndelfgChanging(int value);
    partial void OndelfgChanged();
    partial void OnlastupddtChanging(System.DateTime value);
    partial void OnlastupddtChanged();
    #endregion
		
		public TmPSTeser()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_plantcd", DbType="NVarChar(24) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string plantcd
		{
			get
			{
				return this._plantcd;
			}
			set
			{
				if ((this._plantcd != value))
				{
					this.OnplantcdChanging(value);
					this.SendPropertyChanging();
					this._plantcd = value;
					this.SendPropertyChanged("plantcd");
					this.OnplantcdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_settingtime", DbType="Decimal(18,2) NOT NULL")]
		public decimal settingtime
		{
			get
			{
				return this._settingtime;
			}
			set
			{
				if ((this._settingtime != value))
				{
					this.OnsettingtimeChanging(value);
					this.SendPropertyChanging();
					this._settingtime = value;
					this.SendPropertyChanged("settingtime");
					this.OnsettingtimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_delfg", DbType="Int NOT NULL")]
		public int delfg
		{
			get
			{
				return this._delfg;
			}
			set
			{
				if ((this._delfg != value))
				{
					this.OndelfgChanging(value);
					this.SendPropertyChanging();
					this._delfg = value;
					this.SendPropertyChanged("delfg");
					this.OndelfgChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lastupddt", DbType="DateTime NOT NULL")]
		public System.DateTime lastupddt
		{
			get
			{
				return this._lastupddt;
			}
			set
			{
				if ((this._lastupddt != value))
				{
					this.OnlastupddtChanging(value);
					this.SendPropertyChanging();
					this._lastupddt = value;
					this.SendPropertyChanged("lastupddt");
					this.OnlastupddtChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TnAGVPSTester")]
	public partial class TnAGVPSTester : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _plantcd;
		
		private System.DateTime _testdt;
		
		private string _lotno;
		
		private System.Nullable<System.DateTime> _magazinecheckdt;
		
		private System.Nullable<System.DateTime> _movedt;
		
    #region 拡張メソッドの定義
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnplantcdChanging(string value);
    partial void OnplantcdChanged();
    partial void OntestdtChanging(System.DateTime value);
    partial void OntestdtChanged();
    partial void OnlotnoChanging(string value);
    partial void OnlotnoChanged();
    partial void OnmagazinecheckdtChanging(System.Nullable<System.DateTime> value);
    partial void OnmagazinecheckdtChanged();
    partial void OnmovedtChanging(System.Nullable<System.DateTime> value);
    partial void OnmovedtChanged();
    #endregion
		
		public TnAGVPSTester()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_plantcd", DbType="NVarChar(24) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string plantcd
		{
			get
			{
				return this._plantcd;
			}
			set
			{
				if ((this._plantcd != value))
				{
					this.OnplantcdChanging(value);
					this.SendPropertyChanging();
					this._plantcd = value;
					this.SendPropertyChanged("plantcd");
					this.OnplantcdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_testdt", DbType="DateTime NOT NULL", IsPrimaryKey=true)]
		public System.DateTime testdt
		{
			get
			{
				return this._testdt;
			}
			set
			{
				if ((this._testdt != value))
				{
					this.OntestdtChanging(value);
					this.SendPropertyChanging();
					this._testdt = value;
					this.SendPropertyChanged("testdt");
					this.OntestdtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lotno", DbType="NVarChar(64) NOT NULL", CanBeNull=false)]
		public string lotno
		{
			get
			{
				return this._lotno;
			}
			set
			{
				if ((this._lotno != value))
				{
					this.OnlotnoChanging(value);
					this.SendPropertyChanging();
					this._lotno = value;
					this.SendPropertyChanged("lotno");
					this.OnlotnoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_magazinecheckdt", DbType="DateTime")]
		public System.Nullable<System.DateTime> magazinecheckdt
		{
			get
			{
				return this._magazinecheckdt;
			}
			set
			{
				if ((this._magazinecheckdt != value))
				{
					this.OnmagazinecheckdtChanging(value);
					this.SendPropertyChanging();
					this._magazinecheckdt = value;
					this.SendPropertyChanged("magazinecheckdt");
					this.OnmagazinecheckdtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_movedt", DbType="DateTime")]
		public System.Nullable<System.DateTime> movedt
		{
			get
			{
				return this._movedt;
			}
			set
			{
				if ((this._movedt != value))
				{
					this.OnmovedtChanging(value);
					this.SendPropertyChanging();
					this._movedt = value;
					this.SendPropertyChanged("movedt");
					this.OnmovedtChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TmLineconfigSignalDisplay")]
	public partial class TmLineconfigSignalDisplay : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _flownm;
		
		private int _vieworder;
		
		private string _dispname;
		
		private string _buttoncolor;
		
		private string _plcaddresstagname;
		
		private string _plcporttagname;
		
		private string _plcmakertagname;
		
		private string _hostipadresstagname;
		
		private int _xmlkb;
		
		private string _tagname;
		
		private string _childtagname;
		
		private int _childno;
		
    #region 拡張メソッドの定義
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnflownmChanging(string value);
    partial void OnflownmChanged();
    partial void OnvieworderChanging(int value);
    partial void OnvieworderChanged();
    partial void OndispnameChanging(string value);
    partial void OndispnameChanged();
    partial void OnbuttoncolorChanging(string value);
    partial void OnbuttoncolorChanged();
    partial void OnplcaddresstagnameChanging(string value);
    partial void OnplcaddresstagnameChanged();
    partial void OnplcporttagnameChanging(string value);
    partial void OnplcporttagnameChanged();
    partial void OnplcmakertagnameChanging(string value);
    partial void OnplcmakertagnameChanged();
    partial void OnhostipadresstagnameChanging(string value);
    partial void OnhostipadresstagnameChanged();
    partial void OnxmlkbChanging(int value);
    partial void OnxmlkbChanged();
    partial void OntagnameChanging(string value);
    partial void OntagnameChanged();
    partial void OnchildtagnameChanging(string value);
    partial void OnchildtagnameChanged();
    partial void OnchildnoChanging(int value);
    partial void OnchildnoChanged();
    #endregion
		
		public TmLineconfigSignalDisplay()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_flownm", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string flownm
		{
			get
			{
				return this._flownm;
			}
			set
			{
				if ((this._flownm != value))
				{
					this.OnflownmChanging(value);
					this.SendPropertyChanging();
					this._flownm = value;
					this.SendPropertyChanged("flownm");
					this.OnflownmChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vieworder", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int vieworder
		{
			get
			{
				return this._vieworder;
			}
			set
			{
				if ((this._vieworder != value))
				{
					this.OnvieworderChanging(value);
					this.SendPropertyChanging();
					this._vieworder = value;
					this.SendPropertyChanged("vieworder");
					this.OnvieworderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dispname", DbType="NVarChar(50)")]
		public string dispname
		{
			get
			{
				return this._dispname;
			}
			set
			{
				if ((this._dispname != value))
				{
					this.OndispnameChanging(value);
					this.SendPropertyChanging();
					this._dispname = value;
					this.SendPropertyChanged("dispname");
					this.OndispnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_buttoncolor", DbType="NVarChar(20)")]
		public string buttoncolor
		{
			get
			{
				return this._buttoncolor;
			}
			set
			{
				if ((this._buttoncolor != value))
				{
					this.OnbuttoncolorChanging(value);
					this.SendPropertyChanging();
					this._buttoncolor = value;
					this.SendPropertyChanged("buttoncolor");
					this.OnbuttoncolorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_plcaddresstagname", DbType="NVarChar(50)")]
		public string plcaddresstagname
		{
			get
			{
				return this._plcaddresstagname;
			}
			set
			{
				if ((this._plcaddresstagname != value))
				{
					this.OnplcaddresstagnameChanging(value);
					this.SendPropertyChanging();
					this._plcaddresstagname = value;
					this.SendPropertyChanged("plcaddresstagname");
					this.OnplcaddresstagnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_plcporttagname", DbType="NVarChar(50)")]
		public string plcporttagname
		{
			get
			{
				return this._plcporttagname;
			}
			set
			{
				if ((this._plcporttagname != value))
				{
					this.OnplcporttagnameChanging(value);
					this.SendPropertyChanging();
					this._plcporttagname = value;
					this.SendPropertyChanged("plcporttagname");
					this.OnplcporttagnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_plcmakertagname", DbType="NVarChar(50)")]
		public string plcmakertagname
		{
			get
			{
				return this._plcmakertagname;
			}
			set
			{
				if ((this._plcmakertagname != value))
				{
					this.OnplcmakertagnameChanging(value);
					this.SendPropertyChanging();
					this._plcmakertagname = value;
					this.SendPropertyChanged("plcmakertagname");
					this.OnplcmakertagnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hostipadresstagname", DbType="NVarChar(50)")]
		public string hostipadresstagname
		{
			get
			{
				return this._hostipadresstagname;
			}
			set
			{
				if ((this._hostipadresstagname != value))
				{
					this.OnhostipadresstagnameChanging(value);
					this.SendPropertyChanging();
					this._hostipadresstagname = value;
					this.SendPropertyChanged("hostipadresstagname");
					this.OnhostipadresstagnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_xmlkb", DbType="Int NOT NULL")]
		public int xmlkb
		{
			get
			{
				return this._xmlkb;
			}
			set
			{
				if ((this._xmlkb != value))
				{
					this.OnxmlkbChanging(value);
					this.SendPropertyChanging();
					this._xmlkb = value;
					this.SendPropertyChanged("xmlkb");
					this.OnxmlkbChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tagname", DbType="NVarChar(75) NOT NULL", CanBeNull=false)]
		public string tagname
		{
			get
			{
				return this._tagname;
			}
			set
			{
				if ((this._tagname != value))
				{
					this.OntagnameChanging(value);
					this.SendPropertyChanging();
					this._tagname = value;
					this.SendPropertyChanged("tagname");
					this.OntagnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_childtagname", DbType="NVarChar(75)")]
		public string childtagname
		{
			get
			{
				return this._childtagname;
			}
			set
			{
				if ((this._childtagname != value))
				{
					this.OnchildtagnameChanging(value);
					this.SendPropertyChanging();
					this._childtagname = value;
					this.SendPropertyChanged("childtagname");
					this.OnchildtagnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_childno", DbType="Int NOT NULL")]
		public int childno
		{
			get
			{
				return this._childno;
			}
			set
			{
				if ((this._childno != value))
				{
					this.OnchildnoChanging(value);
					this.SendPropertyChanging();
					this._childno = value;
					this.SendPropertyChanged("childno");
					this.OnchildnoChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TnMoldDischargePressure")]
	public partial class TnMoldDischargePressure : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _moldplantcd;
		
		private string _measurementplantcd;
		
		private System.Nullable<decimal> _dischargepressureval1;
		
		private System.Nullable<decimal> _dischargepressureval2;
		
		private System.Nullable<decimal> _dischargepressureval3;
		
		private System.Nullable<decimal> _dischargepressureval4;
		
		private System.Nullable<decimal> _dischargepressureval5;
		
		private System.Nullable<decimal> _dischargepressureval6;
		
		private System.Nullable<decimal> _dischargepressureval7;
		
		private System.Nullable<decimal> _dischargepressureval8;
		
		private System.Nullable<decimal> _aftercalculationdischargepressureval1;
		
		private System.Nullable<decimal> _aftercalculationdischargepressureval2;
		
		private System.Nullable<decimal> _aftercalculationdischargepressureval3;
		
		private System.Nullable<decimal> _aftercalculationdischargepressureval4;
		
		private System.Nullable<decimal> _aftercalculationdischargepressureval5;
		
		private System.Nullable<decimal> _aftercalculationdischargepressureval6;
		
		private System.Nullable<decimal> _aftercalculationdischargepressureval7;
		
		private System.Nullable<decimal> _aftercalculationdischargepressureval8;
		
		private bool _receivingdonefg;
		
		private bool _moldsendingdonefg;
		
		private System.DateTime _lastupddt;
		
		private bool _voidfg;
		
    #region 拡張メソッドの定義
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmoldplantcdChanging(string value);
    partial void OnmoldplantcdChanged();
    partial void OnmeasurementplantcdChanging(string value);
    partial void OnmeasurementplantcdChanged();
    partial void Ondischargepressureval1Changing(System.Nullable<decimal> value);
    partial void Ondischargepressureval1Changed();
    partial void Ondischargepressureval2Changing(System.Nullable<decimal> value);
    partial void Ondischargepressureval2Changed();
    partial void Ondischargepressureval3Changing(System.Nullable<decimal> value);
    partial void Ondischargepressureval3Changed();
    partial void Ondischargepressureval4Changing(System.Nullable<decimal> value);
    partial void Ondischargepressureval4Changed();
    partial void Ondischargepressureval5Changing(System.Nullable<decimal> value);
    partial void Ondischargepressureval5Changed();
    partial void Ondischargepressureval6Changing(System.Nullable<decimal> value);
    partial void Ondischargepressureval6Changed();
    partial void Ondischargepressureval7Changing(System.Nullable<decimal> value);
    partial void Ondischargepressureval7Changed();
    partial void Ondischargepressureval8Changing(System.Nullable<decimal> value);
    partial void Ondischargepressureval8Changed();
    partial void Onaftercalculationdischargepressureval1Changing(System.Nullable<decimal> value);
    partial void Onaftercalculationdischargepressureval1Changed();
    partial void Onaftercalculationdischargepressureval2Changing(System.Nullable<decimal> value);
    partial void Onaftercalculationdischargepressureval2Changed();
    partial void Onaftercalculationdischargepressureval3Changing(System.Nullable<decimal> value);
    partial void Onaftercalculationdischargepressureval3Changed();
    partial void Onaftercalculationdischargepressureval4Changing(System.Nullable<decimal> value);
    partial void Onaftercalculationdischargepressureval4Changed();
    partial void Onaftercalculationdischargepressureval5Changing(System.Nullable<decimal> value);
    partial void Onaftercalculationdischargepressureval5Changed();
    partial void Onaftercalculationdischargepressureval6Changing(System.Nullable<decimal> value);
    partial void Onaftercalculationdischargepressureval6Changed();
    partial void Onaftercalculationdischargepressureval7Changing(System.Nullable<decimal> value);
    partial void Onaftercalculationdischargepressureval7Changed();
    partial void Onaftercalculationdischargepressureval8Changing(System.Nullable<decimal> value);
    partial void Onaftercalculationdischargepressureval8Changed();
    partial void OnreceivingdonefgChanging(bool value);
    partial void OnreceivingdonefgChanged();
    partial void OnmoldsendingdonefgChanging(bool value);
    partial void OnmoldsendingdonefgChanged();
    partial void OnlastupddtChanging(System.DateTime value);
    partial void OnlastupddtChanged();
    partial void OnvoidfgChanging(bool value);
    partial void OnvoidfgChanged();
    #endregion
		
		public TnMoldDischargePressure()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_moldplantcd", DbType="NVarChar(24) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string moldplantcd
		{
			get
			{
				return this._moldplantcd;
			}
			set
			{
				if ((this._moldplantcd != value))
				{
					this.OnmoldplantcdChanging(value);
					this.SendPropertyChanging();
					this._moldplantcd = value;
					this.SendPropertyChanged("moldplantcd");
					this.OnmoldplantcdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_measurementplantcd", DbType="NVarChar(24)")]
		public string measurementplantcd
		{
			get
			{
				return this._measurementplantcd;
			}
			set
			{
				if ((this._measurementplantcd != value))
				{
					this.OnmeasurementplantcdChanging(value);
					this.SendPropertyChanging();
					this._measurementplantcd = value;
					this.SendPropertyChanged("measurementplantcd");
					this.OnmeasurementplantcdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dischargepressureval1", DbType="Decimal(18,3)")]
		public System.Nullable<decimal> dischargepressureval1
		{
			get
			{
				return this._dischargepressureval1;
			}
			set
			{
				if ((this._dischargepressureval1 != value))
				{
					this.Ondischargepressureval1Changing(value);
					this.SendPropertyChanging();
					this._dischargepressureval1 = value;
					this.SendPropertyChanged("dischargepressureval1");
					this.Ondischargepressureval1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dischargepressureval2", DbType="Decimal(18,3)")]
		public System.Nullable<decimal> dischargepressureval2
		{
			get
			{
				return this._dischargepressureval2;
			}
			set
			{
				if ((this._dischargepressureval2 != value))
				{
					this.Ondischargepressureval2Changing(value);
					this.SendPropertyChanging();
					this._dischargepressureval2 = value;
					this.SendPropertyChanged("dischargepressureval2");
					this.Ondischargepressureval2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dischargepressureval3", DbType="Decimal(18,3)")]
		public System.Nullable<decimal> dischargepressureval3
		{
			get
			{
				return this._dischargepressureval3;
			}
			set
			{
				if ((this._dischargepressureval3 != value))
				{
					this.Ondischargepressureval3Changing(value);
					this.SendPropertyChanging();
					this._dischargepressureval3 = value;
					this.SendPropertyChanged("dischargepressureval3");
					this.Ondischargepressureval3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dischargepressureval4", DbType="Decimal(18,3)")]
		public System.Nullable<decimal> dischargepressureval4
		{
			get
			{
				return this._dischargepressureval4;
			}
			set
			{
				if ((this._dischargepressureval4 != value))
				{
					this.Ondischargepressureval4Changing(value);
					this.SendPropertyChanging();
					this._dischargepressureval4 = value;
					this.SendPropertyChanged("dischargepressureval4");
					this.Ondischargepressureval4Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dischargepressureval5", DbType="Decimal(18,3)")]
		public System.Nullable<decimal> dischargepressureval5
		{
			get
			{
				return this._dischargepressureval5;
			}
			set
			{
				if ((this._dischargepressureval5 != value))
				{
					this.Ondischargepressureval5Changing(value);
					this.SendPropertyChanging();
					this._dischargepressureval5 = value;
					this.SendPropertyChanged("dischargepressureval5");
					this.Ondischargepressureval5Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dischargepressureval6", DbType="Decimal(18,3)")]
		public System.Nullable<decimal> dischargepressureval6
		{
			get
			{
				return this._dischargepressureval6;
			}
			set
			{
				if ((this._dischargepressureval6 != value))
				{
					this.Ondischargepressureval6Changing(value);
					this.SendPropertyChanging();
					this._dischargepressureval6 = value;
					this.SendPropertyChanged("dischargepressureval6");
					this.Ondischargepressureval6Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dischargepressureval7", DbType="Decimal(18,3)")]
		public System.Nullable<decimal> dischargepressureval7
		{
			get
			{
				return this._dischargepressureval7;
			}
			set
			{
				if ((this._dischargepressureval7 != value))
				{
					this.Ondischargepressureval7Changing(value);
					this.SendPropertyChanging();
					this._dischargepressureval7 = value;
					this.SendPropertyChanged("dischargepressureval7");
					this.Ondischargepressureval7Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dischargepressureval8", DbType="Decimal(18,3)")]
		public System.Nullable<decimal> dischargepressureval8
		{
			get
			{
				return this._dischargepressureval8;
			}
			set
			{
				if ((this._dischargepressureval8 != value))
				{
					this.Ondischargepressureval8Changing(value);
					this.SendPropertyChanging();
					this._dischargepressureval8 = value;
					this.SendPropertyChanged("dischargepressureval8");
					this.Ondischargepressureval8Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_aftercalculationdischargepressureval1", DbType="Decimal(18,3)")]
		public System.Nullable<decimal> aftercalculationdischargepressureval1
		{
			get
			{
				return this._aftercalculationdischargepressureval1;
			}
			set
			{
				if ((this._aftercalculationdischargepressureval1 != value))
				{
					this.Onaftercalculationdischargepressureval1Changing(value);
					this.SendPropertyChanging();
					this._aftercalculationdischargepressureval1 = value;
					this.SendPropertyChanged("aftercalculationdischargepressureval1");
					this.Onaftercalculationdischargepressureval1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_aftercalculationdischargepressureval2", DbType="Decimal(18,3)")]
		public System.Nullable<decimal> aftercalculationdischargepressureval2
		{
			get
			{
				return this._aftercalculationdischargepressureval2;
			}
			set
			{
				if ((this._aftercalculationdischargepressureval2 != value))
				{
					this.Onaftercalculationdischargepressureval2Changing(value);
					this.SendPropertyChanging();
					this._aftercalculationdischargepressureval2 = value;
					this.SendPropertyChanged("aftercalculationdischargepressureval2");
					this.Onaftercalculationdischargepressureval2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_aftercalculationdischargepressureval3", DbType="Decimal(18,3)")]
		public System.Nullable<decimal> aftercalculationdischargepressureval3
		{
			get
			{
				return this._aftercalculationdischargepressureval3;
			}
			set
			{
				if ((this._aftercalculationdischargepressureval3 != value))
				{
					this.Onaftercalculationdischargepressureval3Changing(value);
					this.SendPropertyChanging();
					this._aftercalculationdischargepressureval3 = value;
					this.SendPropertyChanged("aftercalculationdischargepressureval3");
					this.Onaftercalculationdischargepressureval3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_aftercalculationdischargepressureval4", DbType="Decimal(18,3)")]
		public System.Nullable<decimal> aftercalculationdischargepressureval4
		{
			get
			{
				return this._aftercalculationdischargepressureval4;
			}
			set
			{
				if ((this._aftercalculationdischargepressureval4 != value))
				{
					this.Onaftercalculationdischargepressureval4Changing(value);
					this.SendPropertyChanging();
					this._aftercalculationdischargepressureval4 = value;
					this.SendPropertyChanged("aftercalculationdischargepressureval4");
					this.Onaftercalculationdischargepressureval4Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_aftercalculationdischargepressureval5", DbType="Decimal(18,3)")]
		public System.Nullable<decimal> aftercalculationdischargepressureval5
		{
			get
			{
				return this._aftercalculationdischargepressureval5;
			}
			set
			{
				if ((this._aftercalculationdischargepressureval5 != value))
				{
					this.Onaftercalculationdischargepressureval5Changing(value);
					this.SendPropertyChanging();
					this._aftercalculationdischargepressureval5 = value;
					this.SendPropertyChanged("aftercalculationdischargepressureval5");
					this.Onaftercalculationdischargepressureval5Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_aftercalculationdischargepressureval6", DbType="Decimal(18,3)")]
		public System.Nullable<decimal> aftercalculationdischargepressureval6
		{
			get
			{
				return this._aftercalculationdischargepressureval6;
			}
			set
			{
				if ((this._aftercalculationdischargepressureval6 != value))
				{
					this.Onaftercalculationdischargepressureval6Changing(value);
					this.SendPropertyChanging();
					this._aftercalculationdischargepressureval6 = value;
					this.SendPropertyChanged("aftercalculationdischargepressureval6");
					this.Onaftercalculationdischargepressureval6Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_aftercalculationdischargepressureval7", DbType="Decimal(18,3)")]
		public System.Nullable<decimal> aftercalculationdischargepressureval7
		{
			get
			{
				return this._aftercalculationdischargepressureval7;
			}
			set
			{
				if ((this._aftercalculationdischargepressureval7 != value))
				{
					this.Onaftercalculationdischargepressureval7Changing(value);
					this.SendPropertyChanging();
					this._aftercalculationdischargepressureval7 = value;
					this.SendPropertyChanged("aftercalculationdischargepressureval7");
					this.Onaftercalculationdischargepressureval7Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_aftercalculationdischargepressureval8", DbType="Decimal(18,3)")]
		public System.Nullable<decimal> aftercalculationdischargepressureval8
		{
			get
			{
				return this._aftercalculationdischargepressureval8;
			}
			set
			{
				if ((this._aftercalculationdischargepressureval8 != value))
				{
					this.Onaftercalculationdischargepressureval8Changing(value);
					this.SendPropertyChanging();
					this._aftercalculationdischargepressureval8 = value;
					this.SendPropertyChanged("aftercalculationdischargepressureval8");
					this.Onaftercalculationdischargepressureval8Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_receivingdonefg", DbType="Bit NOT NULL")]
		public bool receivingdonefg
		{
			get
			{
				return this._receivingdonefg;
			}
			set
			{
				if ((this._receivingdonefg != value))
				{
					this.OnreceivingdonefgChanging(value);
					this.SendPropertyChanging();
					this._receivingdonefg = value;
					this.SendPropertyChanged("receivingdonefg");
					this.OnreceivingdonefgChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_moldsendingdonefg", DbType="Bit NOT NULL")]
		public bool moldsendingdonefg
		{
			get
			{
				return this._moldsendingdonefg;
			}
			set
			{
				if ((this._moldsendingdonefg != value))
				{
					this.OnmoldsendingdonefgChanging(value);
					this.SendPropertyChanging();
					this._moldsendingdonefg = value;
					this.SendPropertyChanged("moldsendingdonefg");
					this.OnmoldsendingdonefgChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lastupddt", DbType="DateTime NOT NULL")]
		public System.DateTime lastupddt
		{
			get
			{
				return this._lastupddt;
			}
			set
			{
				if ((this._lastupddt != value))
				{
					this.OnlastupddtChanging(value);
					this.SendPropertyChanging();
					this._lastupddt = value;
					this.SendPropertyChanged("lastupddt");
					this.OnlastupddtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_voidfg", DbType="Bit NOT NULL")]
		public bool voidfg
		{
			get
			{
				return this._voidfg;
			}
			set
			{
				if ((this._voidfg != value))
				{
					this.OnvoidfgChanging(value);
					this.SendPropertyChanging();
					this._voidfg = value;
					this.SendPropertyChanged("voidfg");
					this.OnvoidfgChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
