//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EICS.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Server=HQDB1.nichia.local\\INST1;Database=SC02_NADB01;Connect Timeout=60;UID={0};P" +
            "WD={1};Application Name=EICS[傾向管理システム];")]
        public string ConnectionString_NASCA {
            get {
                return ((string)(this["ConnectionString_NASCA"]));
            }
            set {
                this["ConnectionString_NASCA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ConnectionString_HONBAN_GA_AUTO {
            get {
                return ((string)(this["ConnectionString_HONBAN_GA_AUTO"]));
            }
            set {
                this["ConnectionString_HONBAN_GA_AUTO"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ConnectionString_HONBAN_MAP_AUTO {
            get {
                return ((string)(this["ConnectionString_HONBAN_MAP_AUTO"]));
            }
            set {
                this["ConnectionString_HONBAN_MAP_AUTO"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Server={2}\\SQLEXPRESS;Database=LENS;Connect Timeout=60;UID={0};PWD={1};Applicatio" +
            "n Name=EICS[傾向管理システム];")]
        public string ConnectionString_LENSDB {
            get {
                return ((string)(this["ConnectionString_LENSDB"]));
            }
            set {
                this["ConnectionString_LENSDB"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://naweb.nichia.local/NPPPublic/NppPublicWebService.asmx")]
        public string EICS_CEJ_local_nichia_naweb_NppPublicWebServiceSoap {
            get {
                return ((string)(this["EICS_CEJ_local_nichia_naweb_NppPublicWebServiceSoap"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Server=CEJDB1.citizen.local\\INST1;Database=QCIL;Connect Timeout=60;UID={0};PWD={1" +
            "};Application Name=EICS[傾向管理システム];")]
        public string ConnectionString_HONBAN_SIDE {
            get {
                return ((string)(this["ConnectionString_HONBAN_SIDE"]));
            }
            set {
                this["ConnectionString_HONBAN_SIDE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Server=CEJDB1.citizen.local\\INST1;Database=NCDB01;UID={0};PWD={1};Application Nam" +
            "e=EICS3[装置情報連携システム];")]
        public string ConnectionString_NCDB {
            get {
                return ((string)(this["ConnectionString_NCDB"]));
            }
            set {
                this["ConnectionString_NCDB"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Server={2}\\SQLEXPRESS;Database=QCIL;Connect Timeout=60;UID={0};PWD={1};Applicatio" +
            "n Name=EICS3[装置情報連携システム];")]
        public string ConnectionString_QCILDB {
            get {
                return ((string)(this["ConnectionString_QCILDB"]));
            }
            set {
                this["ConnectionString_QCILDB"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Server={2}\\SQLEXPRESS;Database=ARMS;Connect Timeout=60;UID={0};PWD={1};Applicatio" +
            "n Name=EICS3[装置情報連携システム];")]
        public string ConnectionString_ARMSDB {
            get {
                return ((string)(this["ConnectionString_ARMSDB"]));
            }
            set {
                this["ConnectionString_ARMSDB"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Server=CEJDB1.citizen.local\\INST1;Database=QCIL;Connect Timeout=60;UID={0};PWD={1" +
            "};Application Name=EICS3[装置情報連携システム];")]
        public string ConnectionString_HONBAN_MAP_HIGH {
            get {
                return ((string)(this["ConnectionString_HONBAN_MAP_HIGH"]));
            }
            set {
                this["ConnectionString_HONBAN_MAP_HIGH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ConnectionString_HONBAN_SIDE_HIGH {
            get {
                return ((string)(this["ConnectionString_HONBAN_SIDE_HIGH"]));
            }
            set {
                this["ConnectionString_HONBAN_SIDE_HIGH"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=SLA-0040-2\\SQLEXPRESS;Initial Catalog=QCIL;Integrated Security=True")]
        public string QCILConnectionString {
            get {
                return ((string)(this["QCILConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=172.21.152.235\\SQLEXPRESS;Initial Catalog=QCIL;Persist Security Info=" +
            "True;User ID=inline;Password=R28uHta")]
        public string QCILConnectionString1 {
            get {
                return ((string)(this["QCILConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=172.21.208.221\\SQLEXPRESS;Initial Catalog=QCIL;Integrated Security=Tr" +
            "ue")]
        public string QCILConnectionString2 {
            get {
                return ((string)(this["QCILConnectionString2"]));
            }
        }
    }
}
