//------------------------------------------------------------------------------
// <auto-generated>
//    このコードはテンプレートから生成されました。
//
//    このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//    このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MAKT
{
    using System;
    using System.Collections.Generic;
    
    public partial class TnMaterial
    {
        public long markdata { get; set; }
        public string typecd { get; set; }
        public string lotno { get; set; }
        public string materialcd { get; set; }
        public string matlotno { get; set; }
        public string plantcd { get; set; }
        public System.DateTime lastupddt { get; set; }
        public int importantfg { get; set; }
    }
}
