//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FVDC.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FVDC.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   DATA No,ﾛｷﾞﾝｸﾞｱﾄﾞﾚｽ（,装置NG：1_WBNG：0（ﾛｷﾞﾝｸﾞ用） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CSV_MM {
            get {
                return ResourceManager.GetString("CSV_MM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DATA No,NGﾏｯﾋﾟﾝｸﾞ 位置,NGﾏｯﾋﾟﾝｸﾞ 判定(NG:1_OK:0),判定 ﾃﾞｨｽﾍﾟﾝｻ1,判定 ﾃﾞｨｽﾍﾟﾝｻ2,判定 ﾃﾞｨｽﾍﾟﾝｻ3,判定 ﾃﾞｨｽﾍﾟﾝｻ4,判定 ﾃﾞｨｽﾍﾟﾝｻ5,判定 ﾃﾞｨｽﾍﾟﾝｻ6,判定 ﾃﾞｨｽﾍﾟﾝｻ7,判定 ﾃﾞｨｽﾍﾟﾝｻ8,吐出時間 ﾃﾞｨｽﾍﾟﾝｻ1,吐出時間 ﾃﾞｨｽﾍﾟﾝｻ2,吐出時間 ﾃﾞｨｽﾍﾟﾝｻ3,吐出時間 ﾃﾞｨｽﾍﾟﾝｻ4,吐出時間 ﾃﾞｨｽﾍﾟﾝｻ5,吐出時間 ﾃﾞｨｽﾍﾟﾝｻ6,吐出時間 ﾃﾞｨｽﾍﾟﾝｻ7,吐出時間 ﾃﾞｨｽﾍﾟﾝｻ8 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CSV_SD {
            get {
                return ResourceManager.GetString("CSV_SD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DATA No,ﾛｷﾞﾝｸﾞｱﾄﾞﾚｽ,処理CD に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CSVME {
            get {
                return ResourceManager.GetString("CSVME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DATA No,ﾛｷﾞﾝｸﾞｱﾄﾞﾚｽ,処理CD に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CSVMM {
            get {
                return ResourceManager.GetString("CSVMM", resourceCulture);
            }
        }
    }
}
