//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArmsApi.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.7.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://naweb.nichia.local/NPPPUBLIC/NppPublicWebService.asmx")]
        public string ArmsApi_local_nichia_naweb_NppPublicWebServiceSoap {
            get {
                return ((string)(this["ArmsApi_local_nichia_naweb_NppPublicWebServiceSoap"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://naweb-dev64/NPPPublic/NppPublicWebService.asmx")]
        public string ArmsApi_test_NppPublicWebServiceSoap {
            get {
                return ((string)(this["ArmsApi_test_NppPublicWebServiceSoap"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=HQDB1\\INST1;Initial Catalog=NADB01;Integrated Security=True")]
        public string NADB01ConnectionString {
            get {
                return ((string)(this["NADB01ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=HQSQDB01\\INST1;Initial Catalog=SQ_EMNG;Persist Security Info=True;Use" +
            "r ID=sla10")]
        public string SQ_EMNGConnectionString {
            get {
                return ((string)(this["SQ_EMNGConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=HQDB101\\INST1;Initial Catalog=NJDB02;Persist Security Info=True;User " +
            "ID=sla06")]
        public string NJDB02ConnectionString {
            get {
                return ((string)(this["NJDB02ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=SLA-0040-2\\SQLEXPRESS;Initial Catalog=ARMS;Integrated Security=True")]
        public string ARMSConnectionString {
            get {
                return ((string)(this["ARMSConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=HQDB101\\INST1;Initial Catalog=NJDB02;Integrated Security=True")]
        public string NJDB02ConnectionString1 {
            get {
                return ((string)(this["NJDB02ConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=172.16.34.201\\SQLEXPRESS;Initial Catalog=QCIL;User ID=inline")]
        public string QCILConnectionString {
            get {
                return ((string)(this["QCILConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=172.21.208.225\\SQLEXPRESS;Initial Catalog=LAMS;Persist Security Info=" +
            "True;User ID=inline")]
        public string LAMSConnectionString {
            get {
                return ((string)(this["LAMSConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=SL5-9742\\SQLEXPRESS;Initial Catalog=ARMS;Persist Security Info=True;U" +
            "ser ID=inline;Password=R28uHta")]
        public string ARMSConnectionString1 {
            get {
                return ((string)(this["ARMSConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=SLA-0040-2\\SQLEXPRESS;Initial Catalog=QCIL;Integrated Security=True")]
        public string QCILConnectionString1 {
            get {
                return ((string)(this["QCILConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=10.129.97.154\\SQLExpress;Initial Catalog=ARMS;User ID=inline")]
        public string ARMSConnectionString2 {
            get {
                return ((string)(this["ARMSConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=10.129.97.154\\SQLEXPRESS;Initial Catalog=ARMS;Persist Security Info=T" +
            "rue;User ID=inline")]
        public string ARMSConnectionString3 {
            get {
                return ((string)(this["ARMSConnectionString3"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=10.129.97.154\\SQLEXPRESS;Initial Catalog=ARMS;Persist Security Info=T" +
            "rue;User ID=inline")]
        public string ARMSConnectionString4 {
            get {
                return ((string)(this["ARMSConnectionString4"]));
            }
        }
    }
}
