//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EICS.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://nmcap1.nmc.local:8173/NPPPublic/NppPublicWebService.asmx")]
        public string EICS_MIK_NascaAPI_NppPublicWebServiceSoap {
            get {
                return ((string)(this["EICS_MIK_NascaAPI_NppPublicWebServiceSoap"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ConnectionString_NCDB {
            get {
                return ((string)(this["ConnectionString_NCDB"]));
            }
            set {
                this["ConnectionString_NCDB"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Server={2}\\SQLEXPRESS;Database=QCIL;Connect Timeout=60;UID={0};PWD={1};Applicatio" +
            "n Name=EICS[傾向管理システム];")]
        public string ConnectionString_QCILDB {
            get {
                return ((string)(this["ConnectionString_QCILDB"]));
            }
            set {
                this["ConnectionString_QCILDB"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Server={2}\\SQLEXPRESS;Database=ARMS;Connect Timeout=60;UID={0};PWD={1};Applicatio" +
            "n Name=EICS[傾向管理システム];")]
        public string ConnectionString_ARMSDB {
            get {
                return ((string)(this["ConnectionString_ARMSDB"]));
            }
            set {
                this["ConnectionString_ARMSDB"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Server=TECDB1.takatsuki.local\\INST1;Database=QCIL01_HIGH_MIK;Connect Timeout=60;U" +
            "ID={0};PWD={1};Application Name=EICS[傾向管理システム];")]
        public string ConnectionString_HONBAN_SIDE {
            get {
                return ((string)(this["ConnectionString_HONBAN_SIDE"]));
            }
            set {
                this["ConnectionString_HONBAN_SIDE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Server=HQDBR1.nichia.local\\INST1;Database=SC06_NADB01;Connect Timeout=60;UID={0};" +
            "PWD={1};Application Name=EICS[傾向管理システム];")]
        public string ConnectionString_NASCA {
            get {
                return ((string)(this["ConnectionString_NASCA"]));
            }
            set {
                this["ConnectionString_NASCA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ConnectionString_HONBAN_MAP_AUTO {
            get {
                return ((string)(this["ConnectionString_HONBAN_MAP_AUTO"]));
            }
            set {
                this["ConnectionString_HONBAN_MAP_AUTO"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Server=TECDB1.takatsuki.local\\INST1;Database=QCIL01_HIGH_MIK;Connect Timeout=60;U" +
            "ID={0};PWD={1};Application Name=EICS[傾向管理システム];")]
        public string ConnectionString_HONBAN_SIDE_HIGH {
            get {
                return ((string)(this["ConnectionString_HONBAN_SIDE_HIGH"]));
            }
            set {
                this["ConnectionString_HONBAN_SIDE_HIGH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ConnectionString_HONBAN_GA_AUTO {
            get {
                return ((string)(this["ConnectionString_HONBAN_GA_AUTO"]));
            }
            set {
                this["ConnectionString_HONBAN_GA_AUTO"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ConnectionString_HONBAN_MAP_HIGH {
            get {
                return ((string)(this["ConnectionString_HONBAN_MAP_HIGH"]));
            }
            set {
                this["ConnectionString_HONBAN_MAP_HIGH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Server={2}\\SQLEXPRESS;Database=LENS;Connect Timeout=60;UID={0};PWD={1};Applicatio" +
            "n Name=EICS[傾向管理システム];")]
        public string ConnectionString_LENSDB {
            get {
                return ((string)(this["ConnectionString_LENSDB"]));
            }
            set {
                this["ConnectionString_LENSDB"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=SLA-0040-2\\SQLEXPRESS;Initial Catalog=QCIL;Integrated Security=True")]
        public string QCILConnectionString {
            get {
                return ((string)(this["QCILConnectionString"]));
            }
        }
    }
}
