//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 1591

namespace GEICS {
    
    
    /// <summary>
    ///Represents a strongly typed in-memory cache of data.
    ///</summary>
    [global::System.Serializable()]
    [global::System.ComponentModel.DesignerCategoryAttribute("code")]
    [global::System.ComponentModel.ToolboxItem(true)]
    [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedDataSetSchema")]
    [global::System.Xml.Serialization.XmlRootAttribute("dsQCIL")]
    [global::System.ComponentModel.Design.HelpKeywordAttribute("vs.data.DataSet")]
    public partial class dsQCIL : global::System.Data.DataSet {
        
        private TvQCILDataTable tableTvQCIL;
        
        private global::System.Data.SchemaSerializationMode _schemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
        public dsQCIL() {
            this.BeginInit();
            this.InitClass();
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            base.Relations.CollectionChanged += schemaChangedHandler;
            this.EndInit();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
        protected dsQCIL(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                base(info, context, false) {
            if ((this.IsBinarySerialized(info, context) == true)) {
                this.InitVars(false);
                global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler1 = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
                this.Tables.CollectionChanged += schemaChangedHandler1;
                this.Relations.CollectionChanged += schemaChangedHandler1;
                return;
            }
            string strSchema = ((string)(info.GetValue("XmlSchema", typeof(string))));
            if ((this.DetermineSchemaSerializationMode(info, context) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
                if ((ds.Tables["TvQCIL"] != null)) {
                    base.Tables.Add(new TvQCILDataTable(ds.Tables["TvQCIL"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
            }
            this.GetSerializationData(info, context);
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
        [global::System.ComponentModel.Browsable(false)]
        [global::System.ComponentModel.DesignerSerializationVisibility(global::System.ComponentModel.DesignerSerializationVisibility.Content)]
        public TvQCILDataTable TvQCIL {
            get {
                return this.tableTvQCIL;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
        [global::System.ComponentModel.BrowsableAttribute(true)]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Visible)]
        public override global::System.Data.SchemaSerializationMode SchemaSerializationMode {
            get {
                return this._schemaSerializationMode;
            }
            set {
                this._schemaSerializationMode = value;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new global::System.Data.DataTableCollection Tables {
            get {
                return base.Tables;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new global::System.Data.DataRelationCollection Relations {
            get {
                return base.Relations;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
        protected override void InitializeDerivedDataSet() {
            this.BeginInit();
            this.InitClass();
            this.EndInit();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
        public override global::System.Data.DataSet Clone() {
            dsQCIL cln = ((dsQCIL)(base.Clone()));
            cln.InitVars();
            cln.SchemaSerializationMode = this.SchemaSerializationMode;
            return cln;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
        protected override bool ShouldSerializeTables() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
        protected override bool ShouldSerializeRelations() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
        protected override void ReadXmlSerializable(global::System.Xml.XmlReader reader) {
            if ((this.DetermineSchemaSerializationMode(reader) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                this.Reset();
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXml(reader);
                if ((ds.Tables["TvQCIL"] != null)) {
                    base.Tables.Add(new TvQCILDataTable(ds.Tables["TvQCIL"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXml(reader);
                this.InitVars();
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
        protected override global::System.Xml.Schema.XmlSchema GetSchemaSerializable() {
            global::System.IO.MemoryStream stream = new global::System.IO.MemoryStream();
            this.WriteXmlSchema(new global::System.Xml.XmlTextWriter(stream, null));
            stream.Position = 0;
            return global::System.Xml.Schema.XmlSchema.Read(new global::System.Xml.XmlTextReader(stream), null);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
        internal void InitVars() {
            this.InitVars(true);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
        internal void InitVars(bool initTable) {
            this.tableTvQCIL = ((TvQCILDataTable)(base.Tables["TvQCIL"]));
            if ((initTable == true)) {
                if ((this.tableTvQCIL != null)) {
                    this.tableTvQCIL.InitVars();
                }
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
        private void InitClass() {
            this.DataSetName = "dsQCIL";
            this.Prefix = "";
            this.Namespace = "http://tempuri.org/dsQCIL.xsd";
            this.EnforceConstraints = true;
            this.SchemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
            this.tableTvQCIL = new TvQCILDataTable();
            base.Tables.Add(this.tableTvQCIL);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
        private bool ShouldSerializeTvQCIL() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
        private void SchemaChanged(object sender, global::System.ComponentModel.CollectionChangeEventArgs e) {
            if ((e.Action == global::System.ComponentModel.CollectionChangeAction.Remove)) {
                this.InitVars();
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
        public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedDataSetSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
            dsQCIL ds = new dsQCIL();
            global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
            global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
            global::System.Xml.Schema.XmlSchemaAny any = new global::System.Xml.Schema.XmlSchemaAny();
            any.Namespace = ds.Namespace;
            sequence.Items.Add(any);
            type.Particle = sequence;
            global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
            if (xs.Contains(dsSchema.TargetNamespace)) {
                global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                try {
                    global::System.Xml.Schema.XmlSchema schema = null;
                    dsSchema.Write(s1);
                    for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                        schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                        s2.SetLength(0);
                        schema.Write(s2);
                        if ((s1.Length == s2.Length)) {
                            s1.Position = 0;
                            s2.Position = 0;
                            for (; ((s1.Position != s1.Length) 
                                        && (s1.ReadByte() == s2.ReadByte())); ) {
                                ;
                            }
                            if ((s1.Position == s1.Length)) {
                                return type;
                            }
                        }
                    }
                }
                finally {
                    if ((s1 != null)) {
                        s1.Close();
                    }
                    if ((s2 != null)) {
                        s2.Close();
                    }
                }
            }
            xs.Add(dsSchema);
            return type;
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
        public delegate void TvQCILRowChangeEventHandler(object sender, TvQCILRowChangeEvent e);
        
        /// <summary>
        ///Represents the strongly named DataTable class.
        ///</summary>
        [global::System.Serializable()]
        [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedTableSchema")]
        public partial class TvQCILDataTable : global::System.Data.TypedTableBase<TvQCILRow> {
            
            private global::System.Data.DataColumn columnInline_CD;
            
            private global::System.Data.DataColumn columnInline_NM;
            
            private global::System.Data.DataColumn columnEquipment_NO;
            
            private global::System.Data.DataColumn columnAssets_NM;
            
            private global::System.Data.DataColumn columnMachinSeq_NO;
            
            private global::System.Data.DataColumn columnModel_NM;
            
            private global::System.Data.DataColumn columnMeasure_DT;
            
            private global::System.Data.DataColumn columnSeq_NO;
            
            private global::System.Data.DataColumn columnQcParam_NO;
            
            private global::System.Data.DataColumn columnMaterial_CD;
            
            private global::System.Data.DataColumn columnClass_NM;
            
            private global::System.Data.DataColumn columnParameter_NM;
            
            private global::System.Data.DataColumn columnManage_NM;
            
            private global::System.Data.DataColumn columnTiming_NM;
            
            private global::System.Data.DataColumn columnParameter_MAX;
            
            private global::System.Data.DataColumn columnParameter_MIN;
            
            private global::System.Data.DataColumn columnDParameter_VAL;
            
            private global::System.Data.DataColumn columnParameter_VAL;
            
            private global::System.Data.DataColumn columnSParameter_VAL;
            
            private global::System.Data.DataColumn columnMagazine_NO;
            
            private global::System.Data.DataColumn columnNascaLot_NO;
            
            private global::System.Data.DataColumn columnMessage_NM;
            
            private global::System.Data.DataColumn columnDS_FG;
            
            private global::System.Data.DataColumn columnCheck_FG;
            
            private global::System.Data.DataColumn columnDel_FG;
            
            private global::System.Data.DataColumn columnUpdUser_CD;
            
            private global::System.Data.DataColumn columnLastUpd_DT;
            
            private global::System.Data.DataColumn columnTargetConfirm_NM;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public TvQCILDataTable() {
                this.TableName = "TvQCIL";
                this.BeginInit();
                this.InitClass();
                this.EndInit();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            internal TvQCILDataTable(global::System.Data.DataTable table) {
                this.TableName = table.TableName;
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            protected TvQCILDataTable(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                    base(info, context) {
                this.InitVars();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public global::System.Data.DataColumn Inline_CDColumn {
                get {
                    return this.columnInline_CD;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public global::System.Data.DataColumn Inline_NMColumn {
                get {
                    return this.columnInline_NM;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public global::System.Data.DataColumn Equipment_NOColumn {
                get {
                    return this.columnEquipment_NO;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public global::System.Data.DataColumn Assets_NMColumn {
                get {
                    return this.columnAssets_NM;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public global::System.Data.DataColumn MachinSeq_NOColumn {
                get {
                    return this.columnMachinSeq_NO;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public global::System.Data.DataColumn Model_NMColumn {
                get {
                    return this.columnModel_NM;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public global::System.Data.DataColumn Measure_DTColumn {
                get {
                    return this.columnMeasure_DT;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public global::System.Data.DataColumn Seq_NOColumn {
                get {
                    return this.columnSeq_NO;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public global::System.Data.DataColumn QcParam_NOColumn {
                get {
                    return this.columnQcParam_NO;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public global::System.Data.DataColumn Material_CDColumn {
                get {
                    return this.columnMaterial_CD;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public global::System.Data.DataColumn Class_NMColumn {
                get {
                    return this.columnClass_NM;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public global::System.Data.DataColumn Parameter_NMColumn {
                get {
                    return this.columnParameter_NM;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public global::System.Data.DataColumn Manage_NMColumn {
                get {
                    return this.columnManage_NM;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public global::System.Data.DataColumn Timing_NMColumn {
                get {
                    return this.columnTiming_NM;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public global::System.Data.DataColumn Parameter_MAXColumn {
                get {
                    return this.columnParameter_MAX;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public global::System.Data.DataColumn Parameter_MINColumn {
                get {
                    return this.columnParameter_MIN;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public global::System.Data.DataColumn DParameter_VALColumn {
                get {
                    return this.columnDParameter_VAL;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public global::System.Data.DataColumn Parameter_VALColumn {
                get {
                    return this.columnParameter_VAL;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public global::System.Data.DataColumn SParameter_VALColumn {
                get {
                    return this.columnSParameter_VAL;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public global::System.Data.DataColumn Magazine_NOColumn {
                get {
                    return this.columnMagazine_NO;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public global::System.Data.DataColumn NascaLot_NOColumn {
                get {
                    return this.columnNascaLot_NO;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public global::System.Data.DataColumn Message_NMColumn {
                get {
                    return this.columnMessage_NM;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public global::System.Data.DataColumn DS_FGColumn {
                get {
                    return this.columnDS_FG;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public global::System.Data.DataColumn Check_FGColumn {
                get {
                    return this.columnCheck_FG;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public global::System.Data.DataColumn Del_FGColumn {
                get {
                    return this.columnDel_FG;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public global::System.Data.DataColumn UpdUser_CDColumn {
                get {
                    return this.columnUpdUser_CD;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public global::System.Data.DataColumn LastUpd_DTColumn {
                get {
                    return this.columnLastUpd_DT;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public global::System.Data.DataColumn TargetConfirm_NMColumn {
                get {
                    return this.columnTargetConfirm_NM;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            [global::System.ComponentModel.Browsable(false)]
            public int Count {
                get {
                    return this.Rows.Count;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public TvQCILRow this[int index] {
                get {
                    return ((TvQCILRow)(this.Rows[index]));
                }
            }
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public event TvQCILRowChangeEventHandler TvQCILRowChanging;
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public event TvQCILRowChangeEventHandler TvQCILRowChanged;
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public event TvQCILRowChangeEventHandler TvQCILRowDeleting;
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public event TvQCILRowChangeEventHandler TvQCILRowDeleted;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public void AddTvQCILRow(TvQCILRow row) {
                this.Rows.Add(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public TvQCILRow AddTvQCILRow(
                        int Inline_CD, 
                        string Inline_NM, 
                        string Equipment_NO, 
                        string Assets_NM, 
                        string MachinSeq_NO, 
                        string Model_NM, 
                        System.DateTime Measure_DT, 
                        int Seq_NO, 
                        int QcParam_NO, 
                        string Material_CD, 
                        string Class_NM, 
                        string Parameter_NM, 
                        string Manage_NM, 
                        string Timing_NM, 
                        decimal Parameter_MAX, 
                        decimal Parameter_MIN, 
                        decimal DParameter_VAL, 
                        string Parameter_VAL, 
                        string SParameter_VAL, 
                        string Magazine_NO, 
                        string NascaLot_NO, 
                        string Message_NM, 
                        bool DS_FG, 
                        bool Check_FG, 
                        bool Del_FG, 
                        string UpdUser_CD, 
                        System.DateTime LastUpd_DT, 
                        string TargetConfirm_NM) {
                TvQCILRow rowTvQCILRow = ((TvQCILRow)(this.NewRow()));
                object[] columnValuesArray = new object[] {
                        Inline_CD,
                        Inline_NM,
                        Equipment_NO,
                        Assets_NM,
                        MachinSeq_NO,
                        Model_NM,
                        Measure_DT,
                        Seq_NO,
                        QcParam_NO,
                        Material_CD,
                        Class_NM,
                        Parameter_NM,
                        Manage_NM,
                        Timing_NM,
                        Parameter_MAX,
                        Parameter_MIN,
                        DParameter_VAL,
                        Parameter_VAL,
                        SParameter_VAL,
                        Magazine_NO,
                        NascaLot_NO,
                        Message_NM,
                        DS_FG,
                        Check_FG,
                        Del_FG,
                        UpdUser_CD,
                        LastUpd_DT,
                        TargetConfirm_NM};
                rowTvQCILRow.ItemArray = columnValuesArray;
                this.Rows.Add(rowTvQCILRow);
                return rowTvQCILRow;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public TvQCILRow FindByInline_CDEquipment_NOMeasure_DTSeq_NOQcParam_NO(int Inline_CD, string Equipment_NO, System.DateTime Measure_DT, int Seq_NO, int QcParam_NO) {
                return ((TvQCILRow)(this.Rows.Find(new object[] {
                            Inline_CD,
                            Equipment_NO,
                            Measure_DT,
                            Seq_NO,
                            QcParam_NO})));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public override global::System.Data.DataTable Clone() {
                TvQCILDataTable cln = ((TvQCILDataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            protected override global::System.Data.DataTable CreateInstance() {
                return new TvQCILDataTable();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            internal void InitVars() {
                this.columnInline_CD = base.Columns["Inline_CD"];
                this.columnInline_NM = base.Columns["Inline_NM"];
                this.columnEquipment_NO = base.Columns["Equipment_NO"];
                this.columnAssets_NM = base.Columns["Assets_NM"];
                this.columnMachinSeq_NO = base.Columns["MachinSeq_NO"];
                this.columnModel_NM = base.Columns["Model_NM"];
                this.columnMeasure_DT = base.Columns["Measure_DT"];
                this.columnSeq_NO = base.Columns["Seq_NO"];
                this.columnQcParam_NO = base.Columns["QcParam_NO"];
                this.columnMaterial_CD = base.Columns["Material_CD"];
                this.columnClass_NM = base.Columns["Class_NM"];
                this.columnParameter_NM = base.Columns["Parameter_NM"];
                this.columnManage_NM = base.Columns["Manage_NM"];
                this.columnTiming_NM = base.Columns["Timing_NM"];
                this.columnParameter_MAX = base.Columns["Parameter_MAX"];
                this.columnParameter_MIN = base.Columns["Parameter_MIN"];
                this.columnDParameter_VAL = base.Columns["DParameter_VAL"];
                this.columnParameter_VAL = base.Columns["Parameter_VAL"];
                this.columnSParameter_VAL = base.Columns["SParameter_VAL"];
                this.columnMagazine_NO = base.Columns["Magazine_NO"];
                this.columnNascaLot_NO = base.Columns["NascaLot_NO"];
                this.columnMessage_NM = base.Columns["Message_NM"];
                this.columnDS_FG = base.Columns["DS_FG"];
                this.columnCheck_FG = base.Columns["Check_FG"];
                this.columnDel_FG = base.Columns["Del_FG"];
                this.columnUpdUser_CD = base.Columns["UpdUser_CD"];
                this.columnLastUpd_DT = base.Columns["LastUpd_DT"];
                this.columnTargetConfirm_NM = base.Columns["TargetConfirm_NM"];
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            private void InitClass() {
                this.columnInline_CD = new global::System.Data.DataColumn("Inline_CD", typeof(int), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnInline_CD);
                this.columnInline_NM = new global::System.Data.DataColumn("Inline_NM", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnInline_NM);
                this.columnEquipment_NO = new global::System.Data.DataColumn("Equipment_NO", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnEquipment_NO);
                this.columnAssets_NM = new global::System.Data.DataColumn("Assets_NM", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnAssets_NM);
                this.columnMachinSeq_NO = new global::System.Data.DataColumn("MachinSeq_NO", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnMachinSeq_NO);
                this.columnModel_NM = new global::System.Data.DataColumn("Model_NM", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnModel_NM);
                this.columnMeasure_DT = new global::System.Data.DataColumn("Measure_DT", typeof(global::System.DateTime), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnMeasure_DT);
                this.columnSeq_NO = new global::System.Data.DataColumn("Seq_NO", typeof(int), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnSeq_NO);
                this.columnQcParam_NO = new global::System.Data.DataColumn("QcParam_NO", typeof(int), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnQcParam_NO);
                this.columnMaterial_CD = new global::System.Data.DataColumn("Material_CD", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnMaterial_CD);
                this.columnClass_NM = new global::System.Data.DataColumn("Class_NM", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnClass_NM);
                this.columnParameter_NM = new global::System.Data.DataColumn("Parameter_NM", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnParameter_NM);
                this.columnManage_NM = new global::System.Data.DataColumn("Manage_NM", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnManage_NM);
                this.columnTiming_NM = new global::System.Data.DataColumn("Timing_NM", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnTiming_NM);
                this.columnParameter_MAX = new global::System.Data.DataColumn("Parameter_MAX", typeof(decimal), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnParameter_MAX);
                this.columnParameter_MIN = new global::System.Data.DataColumn("Parameter_MIN", typeof(decimal), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnParameter_MIN);
                this.columnDParameter_VAL = new global::System.Data.DataColumn("DParameter_VAL", typeof(decimal), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnDParameter_VAL);
                this.columnParameter_VAL = new global::System.Data.DataColumn("Parameter_VAL", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnParameter_VAL);
                this.columnSParameter_VAL = new global::System.Data.DataColumn("SParameter_VAL", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnSParameter_VAL);
                this.columnMagazine_NO = new global::System.Data.DataColumn("Magazine_NO", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnMagazine_NO);
                this.columnNascaLot_NO = new global::System.Data.DataColumn("NascaLot_NO", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnNascaLot_NO);
                this.columnMessage_NM = new global::System.Data.DataColumn("Message_NM", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnMessage_NM);
                this.columnDS_FG = new global::System.Data.DataColumn("DS_FG", typeof(bool), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnDS_FG);
                this.columnCheck_FG = new global::System.Data.DataColumn("Check_FG", typeof(bool), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnCheck_FG);
                this.columnDel_FG = new global::System.Data.DataColumn("Del_FG", typeof(bool), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnDel_FG);
                this.columnUpdUser_CD = new global::System.Data.DataColumn("UpdUser_CD", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnUpdUser_CD);
                this.columnLastUpd_DT = new global::System.Data.DataColumn("LastUpd_DT", typeof(global::System.DateTime), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnLastUpd_DT);
                this.columnTargetConfirm_NM = new global::System.Data.DataColumn("TargetConfirm_NM", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnTargetConfirm_NM);
                this.Constraints.Add(new global::System.Data.UniqueConstraint("TvQCILKey1", new global::System.Data.DataColumn[] {
                                this.columnInline_CD,
                                this.columnEquipment_NO,
                                this.columnMeasure_DT,
                                this.columnSeq_NO,
                                this.columnQcParam_NO}, true));
                this.columnInline_CD.AllowDBNull = false;
                this.columnEquipment_NO.AllowDBNull = false;
                this.columnEquipment_NO.MaxLength = 12;
                this.columnAssets_NM.MaxLength = 100;
                this.columnMachinSeq_NO.MaxLength = 20;
                this.columnModel_NM.AllowDBNull = false;
                this.columnModel_NM.MaxLength = 100;
                this.columnMeasure_DT.AllowDBNull = false;
                this.columnSeq_NO.AllowDBNull = false;
                this.columnQcParam_NO.AllowDBNull = false;
                this.columnMaterial_CD.MaxLength = 24;
                this.columnClass_NM.MaxLength = 20;
                this.columnParameter_NM.MaxLength = 100;
                this.columnManage_NM.MaxLength = 50;
                this.columnTiming_NM.AllowDBNull = false;
                this.columnTiming_NM.MaxLength = 50;
                this.columnParameter_VAL.MaxLength = 100;
                this.columnSParameter_VAL.MaxLength = 100;
                this.columnMagazine_NO.MaxLength = 16;
                this.columnNascaLot_NO.MaxLength = 64;
                this.columnMessage_NM.MaxLength = 200;
                this.columnDS_FG.AllowDBNull = false;
                this.columnCheck_FG.AllowDBNull = false;
                this.columnDel_FG.AllowDBNull = false;
                this.columnUpdUser_CD.MaxLength = 8;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public TvQCILRow NewTvQCILRow() {
                return ((TvQCILRow)(this.NewRow()));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            protected override global::System.Data.DataRow NewRowFromBuilder(global::System.Data.DataRowBuilder builder) {
                return new TvQCILRow(builder);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            protected override global::System.Type GetRowType() {
                return typeof(TvQCILRow);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            protected override void OnRowChanged(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this.TvQCILRowChanged != null)) {
                    this.TvQCILRowChanged(this, new TvQCILRowChangeEvent(((TvQCILRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            protected override void OnRowChanging(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this.TvQCILRowChanging != null)) {
                    this.TvQCILRowChanging(this, new TvQCILRowChangeEvent(((TvQCILRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            protected override void OnRowDeleted(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this.TvQCILRowDeleted != null)) {
                    this.TvQCILRowDeleted(this, new TvQCILRowChangeEvent(((TvQCILRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            protected override void OnRowDeleting(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this.TvQCILRowDeleting != null)) {
                    this.TvQCILRowDeleting(this, new TvQCILRowChangeEvent(((TvQCILRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public void RemoveTvQCILRow(TvQCILRow row) {
                this.Rows.Remove(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedTableSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
                global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
                global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
                dsQCIL ds = new dsQCIL();
                global::System.Xml.Schema.XmlSchemaAny any1 = new global::System.Xml.Schema.XmlSchemaAny();
                any1.Namespace = "http://www.w3.org/2001/XMLSchema";
                any1.MinOccurs = new decimal(0);
                any1.MaxOccurs = decimal.MaxValue;
                any1.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any1);
                global::System.Xml.Schema.XmlSchemaAny any2 = new global::System.Xml.Schema.XmlSchemaAny();
                any2.Namespace = "urn:schemas-microsoft-com:xml-diffgram-v1";
                any2.MinOccurs = new decimal(1);
                any2.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any2);
                global::System.Xml.Schema.XmlSchemaAttribute attribute1 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute1.Name = "namespace";
                attribute1.FixedValue = ds.Namespace;
                type.Attributes.Add(attribute1);
                global::System.Xml.Schema.XmlSchemaAttribute attribute2 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute2.Name = "tableTypeName";
                attribute2.FixedValue = "TvQCILDataTable";
                type.Attributes.Add(attribute2);
                type.Particle = sequence;
                global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
                if (xs.Contains(dsSchema.TargetNamespace)) {
                    global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                    global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                    try {
                        global::System.Xml.Schema.XmlSchema schema = null;
                        dsSchema.Write(s1);
                        for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                            schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                            s2.SetLength(0);
                            schema.Write(s2);
                            if ((s1.Length == s2.Length)) {
                                s1.Position = 0;
                                s2.Position = 0;
                                for (; ((s1.Position != s1.Length) 
                                            && (s1.ReadByte() == s2.ReadByte())); ) {
                                    ;
                                }
                                if ((s1.Position == s1.Length)) {
                                    return type;
                                }
                            }
                        }
                    }
                    finally {
                        if ((s1 != null)) {
                            s1.Close();
                        }
                        if ((s2 != null)) {
                            s2.Close();
                        }
                    }
                }
                xs.Add(dsSchema);
                return type;
            }
        }
        
        /// <summary>
        ///Represents strongly named DataRow class.
        ///</summary>
        public partial class TvQCILRow : global::System.Data.DataRow {
            
            private TvQCILDataTable tableTvQCIL;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            internal TvQCILRow(global::System.Data.DataRowBuilder rb) : 
                    base(rb) {
                this.tableTvQCIL = ((TvQCILDataTable)(this.Table));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public int Inline_CD {
                get {
                    return ((int)(this[this.tableTvQCIL.Inline_CDColumn]));
                }
                set {
                    this[this.tableTvQCIL.Inline_CDColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public string Inline_NM {
                get {
                    try {
                        return ((string)(this[this.tableTvQCIL.Inline_NMColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("テーブル \'TvQCIL\' にある列 \'Inline_NM\' の値は DBNull です。", e);
                    }
                }
                set {
                    this[this.tableTvQCIL.Inline_NMColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public string Equipment_NO {
                get {
                    return ((string)(this[this.tableTvQCIL.Equipment_NOColumn]));
                }
                set {
                    this[this.tableTvQCIL.Equipment_NOColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public string Assets_NM {
                get {
                    try {
                        return ((string)(this[this.tableTvQCIL.Assets_NMColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("テーブル \'TvQCIL\' にある列 \'Assets_NM\' の値は DBNull です。", e);
                    }
                }
                set {
                    this[this.tableTvQCIL.Assets_NMColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public string MachinSeq_NO {
                get {
                    try {
                        return ((string)(this[this.tableTvQCIL.MachinSeq_NOColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("テーブル \'TvQCIL\' にある列 \'MachinSeq_NO\' の値は DBNull です。", e);
                    }
                }
                set {
                    this[this.tableTvQCIL.MachinSeq_NOColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public string Model_NM {
                get {
                    return ((string)(this[this.tableTvQCIL.Model_NMColumn]));
                }
                set {
                    this[this.tableTvQCIL.Model_NMColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public System.DateTime Measure_DT {
                get {
                    return ((global::System.DateTime)(this[this.tableTvQCIL.Measure_DTColumn]));
                }
                set {
                    this[this.tableTvQCIL.Measure_DTColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public int Seq_NO {
                get {
                    return ((int)(this[this.tableTvQCIL.Seq_NOColumn]));
                }
                set {
                    this[this.tableTvQCIL.Seq_NOColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public int QcParam_NO {
                get {
                    return ((int)(this[this.tableTvQCIL.QcParam_NOColumn]));
                }
                set {
                    this[this.tableTvQCIL.QcParam_NOColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public string Material_CD {
                get {
                    try {
                        return ((string)(this[this.tableTvQCIL.Material_CDColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("テーブル \'TvQCIL\' にある列 \'Material_CD\' の値は DBNull です。", e);
                    }
                }
                set {
                    this[this.tableTvQCIL.Material_CDColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public string Class_NM {
                get {
                    try {
                        return ((string)(this[this.tableTvQCIL.Class_NMColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("テーブル \'TvQCIL\' にある列 \'Class_NM\' の値は DBNull です。", e);
                    }
                }
                set {
                    this[this.tableTvQCIL.Class_NMColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public string Parameter_NM {
                get {
                    try {
                        return ((string)(this[this.tableTvQCIL.Parameter_NMColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("テーブル \'TvQCIL\' にある列 \'Parameter_NM\' の値は DBNull です。", e);
                    }
                }
                set {
                    this[this.tableTvQCIL.Parameter_NMColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public string Manage_NM {
                get {
                    try {
                        return ((string)(this[this.tableTvQCIL.Manage_NMColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("テーブル \'TvQCIL\' にある列 \'Manage_NM\' の値は DBNull です。", e);
                    }
                }
                set {
                    this[this.tableTvQCIL.Manage_NMColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public string Timing_NM {
                get {
                    return ((string)(this[this.tableTvQCIL.Timing_NMColumn]));
                }
                set {
                    this[this.tableTvQCIL.Timing_NMColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public decimal Parameter_MAX {
                get {
                    try {
                        return ((decimal)(this[this.tableTvQCIL.Parameter_MAXColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("テーブル \'TvQCIL\' にある列 \'Parameter_MAX\' の値は DBNull です。", e);
                    }
                }
                set {
                    this[this.tableTvQCIL.Parameter_MAXColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public decimal Parameter_MIN {
                get {
                    try {
                        return ((decimal)(this[this.tableTvQCIL.Parameter_MINColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("テーブル \'TvQCIL\' にある列 \'Parameter_MIN\' の値は DBNull です。", e);
                    }
                }
                set {
                    this[this.tableTvQCIL.Parameter_MINColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public decimal DParameter_VAL {
                get {
                    try {
                        return ((decimal)(this[this.tableTvQCIL.DParameter_VALColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("テーブル \'TvQCIL\' にある列 \'DParameter_VAL\' の値は DBNull です。", e);
                    }
                }
                set {
                    this[this.tableTvQCIL.DParameter_VALColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public string Parameter_VAL {
                get {
                    try {
                        return ((string)(this[this.tableTvQCIL.Parameter_VALColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("テーブル \'TvQCIL\' にある列 \'Parameter_VAL\' の値は DBNull です。", e);
                    }
                }
                set {
                    this[this.tableTvQCIL.Parameter_VALColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public string SParameter_VAL {
                get {
                    try {
                        return ((string)(this[this.tableTvQCIL.SParameter_VALColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("テーブル \'TvQCIL\' にある列 \'SParameter_VAL\' の値は DBNull です。", e);
                    }
                }
                set {
                    this[this.tableTvQCIL.SParameter_VALColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public string Magazine_NO {
                get {
                    try {
                        return ((string)(this[this.tableTvQCIL.Magazine_NOColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("テーブル \'TvQCIL\' にある列 \'Magazine_NO\' の値は DBNull です。", e);
                    }
                }
                set {
                    this[this.tableTvQCIL.Magazine_NOColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public string NascaLot_NO {
                get {
                    try {
                        return ((string)(this[this.tableTvQCIL.NascaLot_NOColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("テーブル \'TvQCIL\' にある列 \'NascaLot_NO\' の値は DBNull です。", e);
                    }
                }
                set {
                    this[this.tableTvQCIL.NascaLot_NOColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public string Message_NM {
                get {
                    try {
                        return ((string)(this[this.tableTvQCIL.Message_NMColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("テーブル \'TvQCIL\' にある列 \'Message_NM\' の値は DBNull です。", e);
                    }
                }
                set {
                    this[this.tableTvQCIL.Message_NMColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public bool DS_FG {
                get {
                    return ((bool)(this[this.tableTvQCIL.DS_FGColumn]));
                }
                set {
                    this[this.tableTvQCIL.DS_FGColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public bool Check_FG {
                get {
                    return ((bool)(this[this.tableTvQCIL.Check_FGColumn]));
                }
                set {
                    this[this.tableTvQCIL.Check_FGColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public bool Del_FG {
                get {
                    return ((bool)(this[this.tableTvQCIL.Del_FGColumn]));
                }
                set {
                    this[this.tableTvQCIL.Del_FGColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public string UpdUser_CD {
                get {
                    try {
                        return ((string)(this[this.tableTvQCIL.UpdUser_CDColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("テーブル \'TvQCIL\' にある列 \'UpdUser_CD\' の値は DBNull です。", e);
                    }
                }
                set {
                    this[this.tableTvQCIL.UpdUser_CDColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public System.DateTime LastUpd_DT {
                get {
                    try {
                        return ((global::System.DateTime)(this[this.tableTvQCIL.LastUpd_DTColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("テーブル \'TvQCIL\' にある列 \'LastUpd_DT\' の値は DBNull です。", e);
                    }
                }
                set {
                    this[this.tableTvQCIL.LastUpd_DTColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public string TargetConfirm_NM {
                get {
                    try {
                        return ((string)(this[this.tableTvQCIL.TargetConfirm_NMColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("テーブル \'TvQCIL\' にある列 \'TargetConfirm_NM\' の値は DBNull です。", e);
                    }
                }
                set {
                    this[this.tableTvQCIL.TargetConfirm_NMColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public bool IsInline_NMNull() {
                return this.IsNull(this.tableTvQCIL.Inline_NMColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public void SetInline_NMNull() {
                this[this.tableTvQCIL.Inline_NMColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public bool IsAssets_NMNull() {
                return this.IsNull(this.tableTvQCIL.Assets_NMColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public void SetAssets_NMNull() {
                this[this.tableTvQCIL.Assets_NMColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public bool IsMachinSeq_NONull() {
                return this.IsNull(this.tableTvQCIL.MachinSeq_NOColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public void SetMachinSeq_NONull() {
                this[this.tableTvQCIL.MachinSeq_NOColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public bool IsMaterial_CDNull() {
                return this.IsNull(this.tableTvQCIL.Material_CDColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public void SetMaterial_CDNull() {
                this[this.tableTvQCIL.Material_CDColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public bool IsClass_NMNull() {
                return this.IsNull(this.tableTvQCIL.Class_NMColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public void SetClass_NMNull() {
                this[this.tableTvQCIL.Class_NMColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public bool IsParameter_NMNull() {
                return this.IsNull(this.tableTvQCIL.Parameter_NMColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public void SetParameter_NMNull() {
                this[this.tableTvQCIL.Parameter_NMColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public bool IsManage_NMNull() {
                return this.IsNull(this.tableTvQCIL.Manage_NMColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public void SetManage_NMNull() {
                this[this.tableTvQCIL.Manage_NMColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public bool IsParameter_MAXNull() {
                return this.IsNull(this.tableTvQCIL.Parameter_MAXColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public void SetParameter_MAXNull() {
                this[this.tableTvQCIL.Parameter_MAXColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public bool IsParameter_MINNull() {
                return this.IsNull(this.tableTvQCIL.Parameter_MINColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public void SetParameter_MINNull() {
                this[this.tableTvQCIL.Parameter_MINColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public bool IsDParameter_VALNull() {
                return this.IsNull(this.tableTvQCIL.DParameter_VALColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public void SetDParameter_VALNull() {
                this[this.tableTvQCIL.DParameter_VALColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public bool IsParameter_VALNull() {
                return this.IsNull(this.tableTvQCIL.Parameter_VALColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public void SetParameter_VALNull() {
                this[this.tableTvQCIL.Parameter_VALColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public bool IsSParameter_VALNull() {
                return this.IsNull(this.tableTvQCIL.SParameter_VALColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public void SetSParameter_VALNull() {
                this[this.tableTvQCIL.SParameter_VALColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public bool IsMagazine_NONull() {
                return this.IsNull(this.tableTvQCIL.Magazine_NOColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public void SetMagazine_NONull() {
                this[this.tableTvQCIL.Magazine_NOColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public bool IsNascaLot_NONull() {
                return this.IsNull(this.tableTvQCIL.NascaLot_NOColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public void SetNascaLot_NONull() {
                this[this.tableTvQCIL.NascaLot_NOColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public bool IsMessage_NMNull() {
                return this.IsNull(this.tableTvQCIL.Message_NMColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public void SetMessage_NMNull() {
                this[this.tableTvQCIL.Message_NMColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public bool IsUpdUser_CDNull() {
                return this.IsNull(this.tableTvQCIL.UpdUser_CDColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public void SetUpdUser_CDNull() {
                this[this.tableTvQCIL.UpdUser_CDColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public bool IsLastUpd_DTNull() {
                return this.IsNull(this.tableTvQCIL.LastUpd_DTColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public void SetLastUpd_DTNull() {
                this[this.tableTvQCIL.LastUpd_DTColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public bool IsTargetConfirm_NMNull() {
                return this.IsNull(this.tableTvQCIL.TargetConfirm_NMColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public void SetTargetConfirm_NMNull() {
                this[this.tableTvQCIL.TargetConfirm_NMColumn] = global::System.Convert.DBNull;
            }
        }
        
        /// <summary>
        ///Row event argument class
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
        public class TvQCILRowChangeEvent : global::System.EventArgs {
            
            private TvQCILRow eventRow;
            
            private global::System.Data.DataRowAction eventAction;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public TvQCILRowChangeEvent(TvQCILRow row, global::System.Data.DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public TvQCILRow Row {
                get {
                    return this.eventRow;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public global::System.Data.DataRowAction Action {
                get {
                    return this.eventAction;
                }
            }
        }
    }
}

#pragma warning restore 1591