//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 1591

namespace GEICS {
    
    
    /// <summary>
    ///Represents a strongly typed in-memory cache of data.
    ///</summary>
    [global::System.Serializable()]
    [global::System.ComponentModel.DesignerCategoryAttribute("code")]
    [global::System.ComponentModel.ToolboxItem(true)]
    [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedDataSetSchema")]
    [global::System.Xml.Serialization.XmlRootAttribute("dsTvQCNR")]
    [global::System.ComponentModel.Design.HelpKeywordAttribute("vs.data.DataSet")]
    public partial class dsTvQCNR : global::System.Data.DataSet {
        
        private TvQCNRDataTable tableTvQCNR;
        
        private global::System.Data.SchemaSerializationMode _schemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
        public dsTvQCNR() {
            this.BeginInit();
            this.InitClass();
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            base.Relations.CollectionChanged += schemaChangedHandler;
            this.EndInit();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
        protected dsTvQCNR(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                base(info, context, false) {
            if ((this.IsBinarySerialized(info, context) == true)) {
                this.InitVars(false);
                global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler1 = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
                this.Tables.CollectionChanged += schemaChangedHandler1;
                this.Relations.CollectionChanged += schemaChangedHandler1;
                return;
            }
            string strSchema = ((string)(info.GetValue("XmlSchema", typeof(string))));
            if ((this.DetermineSchemaSerializationMode(info, context) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
                if ((ds.Tables["TvQCNR"] != null)) {
                    base.Tables.Add(new TvQCNRDataTable(ds.Tables["TvQCNR"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
            }
            this.GetSerializationData(info, context);
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
        [global::System.ComponentModel.Browsable(false)]
        [global::System.ComponentModel.DesignerSerializationVisibility(global::System.ComponentModel.DesignerSerializationVisibility.Content)]
        public TvQCNRDataTable TvQCNR {
            get {
                return this.tableTvQCNR;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
        [global::System.ComponentModel.BrowsableAttribute(true)]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Visible)]
        public override global::System.Data.SchemaSerializationMode SchemaSerializationMode {
            get {
                return this._schemaSerializationMode;
            }
            set {
                this._schemaSerializationMode = value;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new global::System.Data.DataTableCollection Tables {
            get {
                return base.Tables;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new global::System.Data.DataRelationCollection Relations {
            get {
                return base.Relations;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
        protected override void InitializeDerivedDataSet() {
            this.BeginInit();
            this.InitClass();
            this.EndInit();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
        public override global::System.Data.DataSet Clone() {
            dsTvQCNR cln = ((dsTvQCNR)(base.Clone()));
            cln.InitVars();
            cln.SchemaSerializationMode = this.SchemaSerializationMode;
            return cln;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
        protected override bool ShouldSerializeTables() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
        protected override bool ShouldSerializeRelations() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
        protected override void ReadXmlSerializable(global::System.Xml.XmlReader reader) {
            if ((this.DetermineSchemaSerializationMode(reader) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                this.Reset();
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXml(reader);
                if ((ds.Tables["TvQCNR"] != null)) {
                    base.Tables.Add(new TvQCNRDataTable(ds.Tables["TvQCNR"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXml(reader);
                this.InitVars();
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
        protected override global::System.Xml.Schema.XmlSchema GetSchemaSerializable() {
            global::System.IO.MemoryStream stream = new global::System.IO.MemoryStream();
            this.WriteXmlSchema(new global::System.Xml.XmlTextWriter(stream, null));
            stream.Position = 0;
            return global::System.Xml.Schema.XmlSchema.Read(new global::System.Xml.XmlTextReader(stream), null);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
        internal void InitVars() {
            this.InitVars(true);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
        internal void InitVars(bool initTable) {
            this.tableTvQCNR = ((TvQCNRDataTable)(base.Tables["TvQCNR"]));
            if ((initTable == true)) {
                if ((this.tableTvQCNR != null)) {
                    this.tableTvQCNR.InitVars();
                }
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
        private void InitClass() {
            this.DataSetName = "dsTvQCNR";
            this.Prefix = "";
            this.Namespace = "http://tempuri.org/dsTvQCNR.xsd";
            this.EnforceConstraints = true;
            this.SchemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
            this.tableTvQCNR = new TvQCNRDataTable();
            base.Tables.Add(this.tableTvQCNR);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
        private bool ShouldSerializeTvQCNR() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
        private void SchemaChanged(object sender, global::System.ComponentModel.CollectionChangeEventArgs e) {
            if ((e.Action == global::System.ComponentModel.CollectionChangeAction.Remove)) {
                this.InitVars();
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
        public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedDataSetSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
            dsTvQCNR ds = new dsTvQCNR();
            global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
            global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
            global::System.Xml.Schema.XmlSchemaAny any = new global::System.Xml.Schema.XmlSchemaAny();
            any.Namespace = ds.Namespace;
            sequence.Items.Add(any);
            type.Particle = sequence;
            global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
            if (xs.Contains(dsSchema.TargetNamespace)) {
                global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                try {
                    global::System.Xml.Schema.XmlSchema schema = null;
                    dsSchema.Write(s1);
                    for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                        schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                        s2.SetLength(0);
                        schema.Write(s2);
                        if ((s1.Length == s2.Length)) {
                            s1.Position = 0;
                            s2.Position = 0;
                            for (; ((s1.Position != s1.Length) 
                                        && (s1.ReadByte() == s2.ReadByte())); ) {
                                ;
                            }
                            if ((s1.Position == s1.Length)) {
                                return type;
                            }
                        }
                    }
                }
                finally {
                    if ((s1 != null)) {
                        s1.Close();
                    }
                    if ((s2 != null)) {
                        s2.Close();
                    }
                }
            }
            xs.Add(dsSchema);
            return type;
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
        public delegate void TvQCNRRowChangeEventHandler(object sender, TvQCNRRowChangeEvent e);
        
        /// <summary>
        ///Represents the strongly named DataTable class.
        ///</summary>
        [global::System.Serializable()]
        [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedTableSchema")]
        public partial class TvQCNRDataTable : global::System.Data.TypedTableBase<TvQCNRRow> {
            
            private global::System.Data.DataColumn columnQCNR_NO;
            
            private global::System.Data.DataColumn columnInline_CD;
            
            private global::System.Data.DataColumn columnEquipment_NO;
            
            private global::System.Data.DataColumn columnNascaLot_NO;
            
            private global::System.Data.DataColumn columnDefect_NO;
            
            private global::System.Data.DataColumn columnDefect_NM;
            
            private global::System.Data.DataColumn columnInspection_NO;
            
            private global::System.Data.DataColumn columnInspection_NM;
            
            private global::System.Data.DataColumn columnProcess_NO;
            
            private global::System.Data.DataColumn columnTiming_NO;
            
            private global::System.Data.DataColumn columnTiming_NM;
            
            private global::System.Data.DataColumn columnMulti_NO;
            
            private global::System.Data.DataColumn columnMeasure_DT;
            
            private global::System.Data.DataColumn columnMessage;
            
            private global::System.Data.DataColumn columnType_CD;
            
            private global::System.Data.DataColumn columnBackNum_NO;
            
            private global::System.Data.DataColumn columnCheck_NO;
            
            private global::System.Data.DataColumn columnUpdUser_CD;
            
            private global::System.Data.DataColumn columnLastUpd_DT;
            
            private global::System.Data.DataColumn columnConfirm_NM;
            
            private global::System.Data.DataColumn columnInline_NM;
            
            private global::System.Data.DataColumn columnAssets_NM;
            
            private global::System.Data.DataColumn columnMagazine_NO;
            
            private global::System.Data.DataColumn columnDBMachine_NM;
            
            private global::System.Data.DataColumn columnWBMachine_NM;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public TvQCNRDataTable() {
                this.TableName = "TvQCNR";
                this.BeginInit();
                this.InitClass();
                this.EndInit();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            internal TvQCNRDataTable(global::System.Data.DataTable table) {
                this.TableName = table.TableName;
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            protected TvQCNRDataTable(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                    base(info, context) {
                this.InitVars();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public global::System.Data.DataColumn QCNR_NOColumn {
                get {
                    return this.columnQCNR_NO;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public global::System.Data.DataColumn Inline_CDColumn {
                get {
                    return this.columnInline_CD;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public global::System.Data.DataColumn Equipment_NOColumn {
                get {
                    return this.columnEquipment_NO;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public global::System.Data.DataColumn NascaLot_NOColumn {
                get {
                    return this.columnNascaLot_NO;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public global::System.Data.DataColumn Defect_NOColumn {
                get {
                    return this.columnDefect_NO;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public global::System.Data.DataColumn Defect_NMColumn {
                get {
                    return this.columnDefect_NM;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public global::System.Data.DataColumn Inspection_NOColumn {
                get {
                    return this.columnInspection_NO;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public global::System.Data.DataColumn Inspection_NMColumn {
                get {
                    return this.columnInspection_NM;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public global::System.Data.DataColumn Process_NOColumn {
                get {
                    return this.columnProcess_NO;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public global::System.Data.DataColumn Timing_NOColumn {
                get {
                    return this.columnTiming_NO;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public global::System.Data.DataColumn Timing_NMColumn {
                get {
                    return this.columnTiming_NM;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public global::System.Data.DataColumn Multi_NOColumn {
                get {
                    return this.columnMulti_NO;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public global::System.Data.DataColumn Measure_DTColumn {
                get {
                    return this.columnMeasure_DT;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public global::System.Data.DataColumn MessageColumn {
                get {
                    return this.columnMessage;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public global::System.Data.DataColumn Type_CDColumn {
                get {
                    return this.columnType_CD;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public global::System.Data.DataColumn BackNum_NOColumn {
                get {
                    return this.columnBackNum_NO;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public global::System.Data.DataColumn Check_NOColumn {
                get {
                    return this.columnCheck_NO;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public global::System.Data.DataColumn UpdUser_CDColumn {
                get {
                    return this.columnUpdUser_CD;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public global::System.Data.DataColumn LastUpd_DTColumn {
                get {
                    return this.columnLastUpd_DT;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public global::System.Data.DataColumn Confirm_NMColumn {
                get {
                    return this.columnConfirm_NM;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public global::System.Data.DataColumn Inline_NMColumn {
                get {
                    return this.columnInline_NM;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public global::System.Data.DataColumn Assets_NMColumn {
                get {
                    return this.columnAssets_NM;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public global::System.Data.DataColumn Magazine_NOColumn {
                get {
                    return this.columnMagazine_NO;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public global::System.Data.DataColumn DBMachine_NMColumn {
                get {
                    return this.columnDBMachine_NM;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public global::System.Data.DataColumn WBMachine_NMColumn {
                get {
                    return this.columnWBMachine_NM;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            [global::System.ComponentModel.Browsable(false)]
            public int Count {
                get {
                    return this.Rows.Count;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public TvQCNRRow this[int index] {
                get {
                    return ((TvQCNRRow)(this.Rows[index]));
                }
            }
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public event TvQCNRRowChangeEventHandler TvQCNRRowChanging;
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public event TvQCNRRowChangeEventHandler TvQCNRRowChanged;
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public event TvQCNRRowChangeEventHandler TvQCNRRowDeleting;
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public event TvQCNRRowChangeEventHandler TvQCNRRowDeleted;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public void AddTvQCNRRow(TvQCNRRow row) {
                this.Rows.Add(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public TvQCNRRow AddTvQCNRRow(
                        int Inline_CD, 
                        string Equipment_NO, 
                        string NascaLot_NO, 
                        int Defect_NO, 
                        string Defect_NM, 
                        int Inspection_NO, 
                        string Inspection_NM, 
                        string Process_NO, 
                        string Timing_NO, 
                        string Timing_NM, 
                        int Multi_NO, 
                        System.DateTime Measure_DT, 
                        string Message, 
                        string Type_CD, 
                        int BackNum_NO, 
                        int Check_NO, 
                        string UpdUser_CD, 
                        System.DateTime LastUpd_DT, 
                        string Confirm_NM, 
                        string Inline_NM, 
                        string Assets_NM, 
                        string Magazine_NO, 
                        string DBMachine_NM, 
                        string WBMachine_NM) {
                TvQCNRRow rowTvQCNRRow = ((TvQCNRRow)(this.NewRow()));
                object[] columnValuesArray = new object[] {
                        null,
                        Inline_CD,
                        Equipment_NO,
                        NascaLot_NO,
                        Defect_NO,
                        Defect_NM,
                        Inspection_NO,
                        Inspection_NM,
                        Process_NO,
                        Timing_NO,
                        Timing_NM,
                        Multi_NO,
                        Measure_DT,
                        Message,
                        Type_CD,
                        BackNum_NO,
                        Check_NO,
                        UpdUser_CD,
                        LastUpd_DT,
                        Confirm_NM,
                        Inline_NM,
                        Assets_NM,
                        Magazine_NO,
                        DBMachine_NM,
                        WBMachine_NM};
                rowTvQCNRRow.ItemArray = columnValuesArray;
                this.Rows.Add(rowTvQCNRRow);
                return rowTvQCNRRow;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public TvQCNRRow FindByQCNR_NO(int QCNR_NO) {
                return ((TvQCNRRow)(this.Rows.Find(new object[] {
                            QCNR_NO})));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public override global::System.Data.DataTable Clone() {
                TvQCNRDataTable cln = ((TvQCNRDataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            protected override global::System.Data.DataTable CreateInstance() {
                return new TvQCNRDataTable();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            internal void InitVars() {
                this.columnQCNR_NO = base.Columns["QCNR_NO"];
                this.columnInline_CD = base.Columns["Inline_CD"];
                this.columnEquipment_NO = base.Columns["Equipment_NO"];
                this.columnNascaLot_NO = base.Columns["NascaLot_NO"];
                this.columnDefect_NO = base.Columns["Defect_NO"];
                this.columnDefect_NM = base.Columns["Defect_NM"];
                this.columnInspection_NO = base.Columns["Inspection_NO"];
                this.columnInspection_NM = base.Columns["Inspection_NM"];
                this.columnProcess_NO = base.Columns["Process_NO"];
                this.columnTiming_NO = base.Columns["Timing_NO"];
                this.columnTiming_NM = base.Columns["Timing_NM"];
                this.columnMulti_NO = base.Columns["Multi_NO"];
                this.columnMeasure_DT = base.Columns["Measure_DT"];
                this.columnMessage = base.Columns["Message"];
                this.columnType_CD = base.Columns["Type_CD"];
                this.columnBackNum_NO = base.Columns["BackNum_NO"];
                this.columnCheck_NO = base.Columns["Check_NO"];
                this.columnUpdUser_CD = base.Columns["UpdUser_CD"];
                this.columnLastUpd_DT = base.Columns["LastUpd_DT"];
                this.columnConfirm_NM = base.Columns["Confirm_NM"];
                this.columnInline_NM = base.Columns["Inline_NM"];
                this.columnAssets_NM = base.Columns["Assets_NM"];
                this.columnMagazine_NO = base.Columns["Magazine_NO"];
                this.columnDBMachine_NM = base.Columns["DBMachine_NM"];
                this.columnWBMachine_NM = base.Columns["WBMachine_NM"];
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            private void InitClass() {
                this.columnQCNR_NO = new global::System.Data.DataColumn("QCNR_NO", typeof(int), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnQCNR_NO);
                this.columnInline_CD = new global::System.Data.DataColumn("Inline_CD", typeof(int), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnInline_CD);
                this.columnEquipment_NO = new global::System.Data.DataColumn("Equipment_NO", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnEquipment_NO);
                this.columnNascaLot_NO = new global::System.Data.DataColumn("NascaLot_NO", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnNascaLot_NO);
                this.columnDefect_NO = new global::System.Data.DataColumn("Defect_NO", typeof(int), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnDefect_NO);
                this.columnDefect_NM = new global::System.Data.DataColumn("Defect_NM", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnDefect_NM);
                this.columnInspection_NO = new global::System.Data.DataColumn("Inspection_NO", typeof(int), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnInspection_NO);
                this.columnInspection_NM = new global::System.Data.DataColumn("Inspection_NM", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnInspection_NM);
                this.columnProcess_NO = new global::System.Data.DataColumn("Process_NO", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnProcess_NO);
                this.columnTiming_NO = new global::System.Data.DataColumn("Timing_NO", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnTiming_NO);
                this.columnTiming_NM = new global::System.Data.DataColumn("Timing_NM", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnTiming_NM);
                this.columnMulti_NO = new global::System.Data.DataColumn("Multi_NO", typeof(int), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnMulti_NO);
                this.columnMeasure_DT = new global::System.Data.DataColumn("Measure_DT", typeof(global::System.DateTime), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnMeasure_DT);
                this.columnMessage = new global::System.Data.DataColumn("Message", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnMessage);
                this.columnType_CD = new global::System.Data.DataColumn("Type_CD", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnType_CD);
                this.columnBackNum_NO = new global::System.Data.DataColumn("BackNum_NO", typeof(int), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnBackNum_NO);
                this.columnCheck_NO = new global::System.Data.DataColumn("Check_NO", typeof(int), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnCheck_NO);
                this.columnUpdUser_CD = new global::System.Data.DataColumn("UpdUser_CD", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnUpdUser_CD);
                this.columnLastUpd_DT = new global::System.Data.DataColumn("LastUpd_DT", typeof(global::System.DateTime), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnLastUpd_DT);
                this.columnConfirm_NM = new global::System.Data.DataColumn("Confirm_NM", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnConfirm_NM);
                this.columnInline_NM = new global::System.Data.DataColumn("Inline_NM", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnInline_NM);
                this.columnAssets_NM = new global::System.Data.DataColumn("Assets_NM", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnAssets_NM);
                this.columnMagazine_NO = new global::System.Data.DataColumn("Magazine_NO", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnMagazine_NO);
                this.columnDBMachine_NM = new global::System.Data.DataColumn("DBMachine_NM", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnDBMachine_NM);
                this.columnWBMachine_NM = new global::System.Data.DataColumn("WBMachine_NM", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnWBMachine_NM);
                this.Constraints.Add(new global::System.Data.UniqueConstraint("Constraint1", new global::System.Data.DataColumn[] {
                                this.columnQCNR_NO}, true));
                this.columnQCNR_NO.AutoIncrement = true;
                this.columnQCNR_NO.AutoIncrementSeed = -1;
                this.columnQCNR_NO.AutoIncrementStep = -1;
                this.columnQCNR_NO.AllowDBNull = false;
                this.columnQCNR_NO.ReadOnly = true;
                this.columnQCNR_NO.Unique = true;
                this.columnInline_CD.AllowDBNull = false;
                this.columnEquipment_NO.AllowDBNull = false;
                this.columnEquipment_NO.MaxLength = 20;
                this.columnNascaLot_NO.AllowDBNull = false;
                this.columnNascaLot_NO.MaxLength = 64;
                this.columnDefect_NO.AllowDBNull = false;
                this.columnDefect_NM.AllowDBNull = false;
                this.columnDefect_NM.MaxLength = 100;
                this.columnInspection_NO.AllowDBNull = false;
                this.columnInspection_NM.AllowDBNull = false;
                this.columnInspection_NM.MaxLength = 100;
                this.columnProcess_NO.AllowDBNull = false;
                this.columnTiming_NO.AllowDBNull = false;
                this.columnTiming_NO.MaxLength = 10;
                this.columnTiming_NM.AllowDBNull = false;
                this.columnTiming_NM.MaxLength = 20;
                this.columnMulti_NO.AllowDBNull = false;
                this.columnMeasure_DT.AllowDBNull = false;
                this.columnMessage.AllowDBNull = false;
                this.columnMessage.MaxLength = 50;
                this.columnType_CD.AllowDBNull = false;
                this.columnType_CD.MaxLength = 24;
                this.columnBackNum_NO.AllowDBNull = false;
                this.columnCheck_NO.AllowDBNull = false;
                this.columnUpdUser_CD.AllowDBNull = false;
                this.columnUpdUser_CD.MaxLength = 10;
                this.columnLastUpd_DT.AllowDBNull = false;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public TvQCNRRow NewTvQCNRRow() {
                return ((TvQCNRRow)(this.NewRow()));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            protected override global::System.Data.DataRow NewRowFromBuilder(global::System.Data.DataRowBuilder builder) {
                return new TvQCNRRow(builder);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            protected override global::System.Type GetRowType() {
                return typeof(TvQCNRRow);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            protected override void OnRowChanged(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this.TvQCNRRowChanged != null)) {
                    this.TvQCNRRowChanged(this, new TvQCNRRowChangeEvent(((TvQCNRRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            protected override void OnRowChanging(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this.TvQCNRRowChanging != null)) {
                    this.TvQCNRRowChanging(this, new TvQCNRRowChangeEvent(((TvQCNRRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            protected override void OnRowDeleted(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this.TvQCNRRowDeleted != null)) {
                    this.TvQCNRRowDeleted(this, new TvQCNRRowChangeEvent(((TvQCNRRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            protected override void OnRowDeleting(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this.TvQCNRRowDeleting != null)) {
                    this.TvQCNRRowDeleting(this, new TvQCNRRowChangeEvent(((TvQCNRRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public void RemoveTvQCNRRow(TvQCNRRow row) {
                this.Rows.Remove(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedTableSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
                global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
                global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
                dsTvQCNR ds = new dsTvQCNR();
                global::System.Xml.Schema.XmlSchemaAny any1 = new global::System.Xml.Schema.XmlSchemaAny();
                any1.Namespace = "http://www.w3.org/2001/XMLSchema";
                any1.MinOccurs = new decimal(0);
                any1.MaxOccurs = decimal.MaxValue;
                any1.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any1);
                global::System.Xml.Schema.XmlSchemaAny any2 = new global::System.Xml.Schema.XmlSchemaAny();
                any2.Namespace = "urn:schemas-microsoft-com:xml-diffgram-v1";
                any2.MinOccurs = new decimal(1);
                any2.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any2);
                global::System.Xml.Schema.XmlSchemaAttribute attribute1 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute1.Name = "namespace";
                attribute1.FixedValue = ds.Namespace;
                type.Attributes.Add(attribute1);
                global::System.Xml.Schema.XmlSchemaAttribute attribute2 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute2.Name = "tableTypeName";
                attribute2.FixedValue = "TvQCNRDataTable";
                type.Attributes.Add(attribute2);
                type.Particle = sequence;
                global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
                if (xs.Contains(dsSchema.TargetNamespace)) {
                    global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                    global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                    try {
                        global::System.Xml.Schema.XmlSchema schema = null;
                        dsSchema.Write(s1);
                        for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                            schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                            s2.SetLength(0);
                            schema.Write(s2);
                            if ((s1.Length == s2.Length)) {
                                s1.Position = 0;
                                s2.Position = 0;
                                for (; ((s1.Position != s1.Length) 
                                            && (s1.ReadByte() == s2.ReadByte())); ) {
                                    ;
                                }
                                if ((s1.Position == s1.Length)) {
                                    return type;
                                }
                            }
                        }
                    }
                    finally {
                        if ((s1 != null)) {
                            s1.Close();
                        }
                        if ((s2 != null)) {
                            s2.Close();
                        }
                    }
                }
                xs.Add(dsSchema);
                return type;
            }
        }
        
        /// <summary>
        ///Represents strongly named DataRow class.
        ///</summary>
        public partial class TvQCNRRow : global::System.Data.DataRow {
            
            private TvQCNRDataTable tableTvQCNR;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            internal TvQCNRRow(global::System.Data.DataRowBuilder rb) : 
                    base(rb) {
                this.tableTvQCNR = ((TvQCNRDataTable)(this.Table));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public int QCNR_NO {
                get {
                    return ((int)(this[this.tableTvQCNR.QCNR_NOColumn]));
                }
                set {
                    this[this.tableTvQCNR.QCNR_NOColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public int Inline_CD {
                get {
                    return ((int)(this[this.tableTvQCNR.Inline_CDColumn]));
                }
                set {
                    this[this.tableTvQCNR.Inline_CDColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public string Equipment_NO {
                get {
                    return ((string)(this[this.tableTvQCNR.Equipment_NOColumn]));
                }
                set {
                    this[this.tableTvQCNR.Equipment_NOColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public string NascaLot_NO {
                get {
                    return ((string)(this[this.tableTvQCNR.NascaLot_NOColumn]));
                }
                set {
                    this[this.tableTvQCNR.NascaLot_NOColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public int Defect_NO {
                get {
                    return ((int)(this[this.tableTvQCNR.Defect_NOColumn]));
                }
                set {
                    this[this.tableTvQCNR.Defect_NOColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public string Defect_NM {
                get {
                    return ((string)(this[this.tableTvQCNR.Defect_NMColumn]));
                }
                set {
                    this[this.tableTvQCNR.Defect_NMColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public int Inspection_NO {
                get {
                    return ((int)(this[this.tableTvQCNR.Inspection_NOColumn]));
                }
                set {
                    this[this.tableTvQCNR.Inspection_NOColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public string Inspection_NM {
                get {
                    return ((string)(this[this.tableTvQCNR.Inspection_NMColumn]));
                }
                set {
                    this[this.tableTvQCNR.Inspection_NMColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public string Process_NO {
                get {
                    return ((string)(this[this.tableTvQCNR.Process_NOColumn]));
                }
                set {
                    this[this.tableTvQCNR.Process_NOColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public string Timing_NO {
                get {
                    return ((string)(this[this.tableTvQCNR.Timing_NOColumn]));
                }
                set {
                    this[this.tableTvQCNR.Timing_NOColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public string Timing_NM {
                get {
                    return ((string)(this[this.tableTvQCNR.Timing_NMColumn]));
                }
                set {
                    this[this.tableTvQCNR.Timing_NMColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public int Multi_NO {
                get {
                    return ((int)(this[this.tableTvQCNR.Multi_NOColumn]));
                }
                set {
                    this[this.tableTvQCNR.Multi_NOColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public System.DateTime Measure_DT {
                get {
                    return ((global::System.DateTime)(this[this.tableTvQCNR.Measure_DTColumn]));
                }
                set {
                    this[this.tableTvQCNR.Measure_DTColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public string Message {
                get {
                    return ((string)(this[this.tableTvQCNR.MessageColumn]));
                }
                set {
                    this[this.tableTvQCNR.MessageColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public string Type_CD {
                get {
                    return ((string)(this[this.tableTvQCNR.Type_CDColumn]));
                }
                set {
                    this[this.tableTvQCNR.Type_CDColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public int BackNum_NO {
                get {
                    return ((int)(this[this.tableTvQCNR.BackNum_NOColumn]));
                }
                set {
                    this[this.tableTvQCNR.BackNum_NOColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public int Check_NO {
                get {
                    return ((int)(this[this.tableTvQCNR.Check_NOColumn]));
                }
                set {
                    this[this.tableTvQCNR.Check_NOColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public string UpdUser_CD {
                get {
                    return ((string)(this[this.tableTvQCNR.UpdUser_CDColumn]));
                }
                set {
                    this[this.tableTvQCNR.UpdUser_CDColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public System.DateTime LastUpd_DT {
                get {
                    return ((global::System.DateTime)(this[this.tableTvQCNR.LastUpd_DTColumn]));
                }
                set {
                    this[this.tableTvQCNR.LastUpd_DTColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public string Confirm_NM {
                get {
                    try {
                        return ((string)(this[this.tableTvQCNR.Confirm_NMColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("テーブル \'TvQCNR\' にある列 \'Confirm_NM\' の値は DBNull です。", e);
                    }
                }
                set {
                    this[this.tableTvQCNR.Confirm_NMColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public string Inline_NM {
                get {
                    try {
                        return ((string)(this[this.tableTvQCNR.Inline_NMColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("テーブル \'TvQCNR\' にある列 \'Inline_NM\' の値は DBNull です。", e);
                    }
                }
                set {
                    this[this.tableTvQCNR.Inline_NMColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public string Assets_NM {
                get {
                    try {
                        return ((string)(this[this.tableTvQCNR.Assets_NMColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("テーブル \'TvQCNR\' にある列 \'Assets_NM\' の値は DBNull です。", e);
                    }
                }
                set {
                    this[this.tableTvQCNR.Assets_NMColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public string Magazine_NO {
                get {
                    try {
                        return ((string)(this[this.tableTvQCNR.Magazine_NOColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("テーブル \'TvQCNR\' にある列 \'Magazine_NO\' の値は DBNull です。", e);
                    }
                }
                set {
                    this[this.tableTvQCNR.Magazine_NOColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public string DBMachine_NM {
                get {
                    try {
                        return ((string)(this[this.tableTvQCNR.DBMachine_NMColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("テーブル \'TvQCNR\' にある列 \'DBMachine_NM\' の値は DBNull です。", e);
                    }
                }
                set {
                    this[this.tableTvQCNR.DBMachine_NMColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public string WBMachine_NM {
                get {
                    try {
                        return ((string)(this[this.tableTvQCNR.WBMachine_NMColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("テーブル \'TvQCNR\' にある列 \'WBMachine_NM\' の値は DBNull です。", e);
                    }
                }
                set {
                    this[this.tableTvQCNR.WBMachine_NMColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public bool IsConfirm_NMNull() {
                return this.IsNull(this.tableTvQCNR.Confirm_NMColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public void SetConfirm_NMNull() {
                this[this.tableTvQCNR.Confirm_NMColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public bool IsInline_NMNull() {
                return this.IsNull(this.tableTvQCNR.Inline_NMColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public void SetInline_NMNull() {
                this[this.tableTvQCNR.Inline_NMColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public bool IsAssets_NMNull() {
                return this.IsNull(this.tableTvQCNR.Assets_NMColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public void SetAssets_NMNull() {
                this[this.tableTvQCNR.Assets_NMColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public bool IsMagazine_NONull() {
                return this.IsNull(this.tableTvQCNR.Magazine_NOColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public void SetMagazine_NONull() {
                this[this.tableTvQCNR.Magazine_NOColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public bool IsDBMachine_NMNull() {
                return this.IsNull(this.tableTvQCNR.DBMachine_NMColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public void SetDBMachine_NMNull() {
                this[this.tableTvQCNR.DBMachine_NMColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public bool IsWBMachine_NMNull() {
                return this.IsNull(this.tableTvQCNR.WBMachine_NMColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public void SetWBMachine_NMNull() {
                this[this.tableTvQCNR.WBMachine_NMColumn] = global::System.Convert.DBNull;
            }
        }
        
        /// <summary>
        ///Row event argument class
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
        public class TvQCNRRowChangeEvent : global::System.EventArgs {
            
            private TvQCNRRow eventRow;
            
            private global::System.Data.DataRowAction eventAction;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public TvQCNRRowChangeEvent(TvQCNRRow row, global::System.Data.DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public TvQCNRRow Row {
                get {
                    return this.eventRow;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")]
            public global::System.Data.DataRowAction Action {
                get {
                    return this.eventAction;
                }
            }
        }
    }
}

#pragma warning restore 1591