<?xml version="1.0" encoding="utf-8"?><Database Name="QCIL" Class="EICSDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=SLA-0040-2\SQLEXPRESS;Initial Catalog=QCIL;Integrated Security=True" SettingsObjectName="ArmsApi.Properties.Settings" SettingsPropertyName="QCILConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.TmLSET" Member="TmLSET">
    <Type Name="TmLSET">
      <Column Name="Inline_CD" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Equipment_NO" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Equipment_CD" Type="System.String" DbType="Char(12) NOT NULL" CanBeNull="false" />
      <Column Name="Process_CD" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Seq_NO" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IPAddress_NO" Type="System.String" DbType="Char(15) NOT NULL" CanBeNull="false" />
      <Column Name="Port_NO" Type="System.String" DbType="Char(8)" CanBeNull="true" />
      <Column Name="InputFolder_NM" Type="System.String" DbType="Char(128)" CanBeNull="true" />
      <Column Name="LoaderAddress_NO" Type="System.String" DbType="Char(15)" CanBeNull="true" />
      <Column Name="LoaderPlcNode_NO" Type="System.String" DbType="Char(15)" CanBeNull="true" />
      <Column Name="Del_FG" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="UpdUser_CD" Type="System.String" DbType="Char(8) NOT NULL" CanBeNull="false" />
      <Column Name="LastUpd_DT" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="ThreadGrp_CD" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="MainThread_FG" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="EquipPart_ID" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="WorkingType_CD" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ArmsTypeNoCheck_FG" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="ReferMultiServer_FG" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="EnableResultPriorityJudge_FG" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="WorkingTypeGroup_CD" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Chip_NM" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.TmTypeGroup" Member="TmTypeGroup">
    <Type Name="TmTypeGroup">
      <Column Name="Model_NM" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Type_CD" Type="System.String" DbType="NVarChar(64) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Chip_NM" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TypeGroup_CD" Type="System.String" DbType="NVarChar(64) NOT NULL" CanBeNull="false" />
      <Column Name="Del_FG" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="UpdUser_CD" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="LastUpd_DT" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.TmEQUI" Member="TmEQUI">
    <Type Name="TmEQUI">
      <Column Name="Equipment_NO" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Model_NM" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Assets_NM" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="MachinSeq_NO" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Del_FG" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="UpdUser_CD" Type="System.String" DbType="Char(8)" CanBeNull="true" />
      <Column Name="LastUpd_DT" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.TnPsMeasureResult" Member="TnPsMeasureResult">
    <Type Name="TnPsMeasureResult">
      <Column Name="Tray_NO" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Sheet_NO" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="QcParam_NO" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Plant_CD" Type="System.String" DbType="NVarChar(24) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Measure_DT" Type="System.DateTime" DbType="DateTime NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Type_CD" Type="System.String" DbType="NVarChar(24) NOT NULL" CanBeNull="false" />
      <Column Name="Lot_NO" Type="System.String" DbType="NVarChar(64)" CanBeNull="true" />
      <Column Name="MeasureAve_VAL" Type="System.Decimal" DbType="Decimal(18,7) NOT NULL" CanBeNull="false" />
      <Column Name="New_FG" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="LastUpd_DT" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>