<?xml version="1.0" encoding="utf-8"?><Database Name="LAMS" Class="LAMSDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=172.21.208.225\SQLEXPRESS;Initial Catalog=LAMS;Persist Security Info=True;User ID=inline" SettingsObjectName="ArmsApi.Properties.Settings" SettingsPropertyName="LAMSConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.TnMachineRequire" Member="TnMachineRequire">
    <Type Name="TnMachineRequire">
      <Column Name="plantcd" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="requireinputfg" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="inputforbiddenfg" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="lastupddt" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>