#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArmsApi.Model.DataContext
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="NADB01")]
	public partial class NASCADataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region 拡張メソッドの定義
    partial void OnCreated();
    partial void InsertNttDITK(NttDITK instance);
    partial void UpdateNttDITK(NttDITK instance);
    partial void DeleteNttDITK(NttDITK instance);
    partial void InsertNttRING(NttRING instance);
    partial void UpdateNttRING(NttRING instance);
    partial void DeleteNttRING(NttRING instance);
    #endregion
		
		public NASCADataContext() : 
				base(global::ArmsApi.Properties.Settings.Default.NADB01ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public NASCADataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public NASCADataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public NASCADataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public NASCADataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<NttDITK> NttDITK
		{
			get
			{
				return this.GetTable<NttDITK>();
			}
		}
		
		public System.Data.Linq.Table<NttRING> NttRING
		{
			get
			{
				return this.GetTable<NttRING>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NttDITK")]
	public partial class NttDITK : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _DiceLot_ID;
		
		private string _RootsLot_NO;
		
		private string _UserLot_NO;
		
		private string _Material_CD;
		
		private string _DiceSelection_NM;
		
		private string _DiceRank_NM;
		
		private string _Inka_NM;
		
		private float _Wd_MIN;
		
		private float _Wd_MAX;
		
		private float _Wd_AVE;
		
		private float _Wd_STD;
		
		private float _Wp_MIN;
		
		private float _Wp_MAX;
		
		private float _Wp_AVE;
		
		private float _Wp_STD;
		
		private float _Po_MIN;
		
		private float _Po_MAX;
		
		private float _Po_AVE;
		
		private float _Po_STD;
		
		private float _Vf_MIN;
		
		private float _Vf_MAX;
		
		private float _Vf_AVE;
		
		private float _Vf_STD;
		
		private float _Iv_MIN;
		
		private float _Iv_MAX;
		
		private float _Iv_AVE;
		
		private float _Iv_STD;
		
		private float _Vl3_MIN;
		
		private float _Vl3_MAX;
		
		private float _Vl3_AVE;
		
		private float _Vl3_STD;
		
		private bool _Del_FG;
		
		private string _UpdUser_CD;
		
		private System.DateTime _LastUpd_DT;
		
		private float _Thickness_AVE;
		
		private string _Supply_ID;
		
		private decimal _ChipQty_CT;
		
		private float _WaveAve_VAL;
		
		private float _WaveStd_VAL;
		
		private string _WaveCpt_NM;
		
    #region 拡張メソッドの定義
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnDiceLot_IDChanging(int value);
    partial void OnDiceLot_IDChanged();
    partial void OnRootsLot_NOChanging(string value);
    partial void OnRootsLot_NOChanged();
    partial void OnUserLot_NOChanging(string value);
    partial void OnUserLot_NOChanged();
    partial void OnMaterial_CDChanging(string value);
    partial void OnMaterial_CDChanged();
    partial void OnDiceSelection_NMChanging(string value);
    partial void OnDiceSelection_NMChanged();
    partial void OnDiceRank_NMChanging(string value);
    partial void OnDiceRank_NMChanged();
    partial void OnInka_NMChanging(string value);
    partial void OnInka_NMChanged();
    partial void OnWd_MINChanging(float value);
    partial void OnWd_MINChanged();
    partial void OnWd_MAXChanging(float value);
    partial void OnWd_MAXChanged();
    partial void OnWd_AVEChanging(float value);
    partial void OnWd_AVEChanged();
    partial void OnWd_STDChanging(float value);
    partial void OnWd_STDChanged();
    partial void OnWp_MINChanging(float value);
    partial void OnWp_MINChanged();
    partial void OnWp_MAXChanging(float value);
    partial void OnWp_MAXChanged();
    partial void OnWp_AVEChanging(float value);
    partial void OnWp_AVEChanged();
    partial void OnWp_STDChanging(float value);
    partial void OnWp_STDChanged();
    partial void OnPo_MINChanging(float value);
    partial void OnPo_MINChanged();
    partial void OnPo_MAXChanging(float value);
    partial void OnPo_MAXChanged();
    partial void OnPo_AVEChanging(float value);
    partial void OnPo_AVEChanged();
    partial void OnPo_STDChanging(float value);
    partial void OnPo_STDChanged();
    partial void OnVf_MINChanging(float value);
    partial void OnVf_MINChanged();
    partial void OnVf_MAXChanging(float value);
    partial void OnVf_MAXChanged();
    partial void OnVf_AVEChanging(float value);
    partial void OnVf_AVEChanged();
    partial void OnVf_STDChanging(float value);
    partial void OnVf_STDChanged();
    partial void OnIv_MINChanging(float value);
    partial void OnIv_MINChanged();
    partial void OnIv_MAXChanging(float value);
    partial void OnIv_MAXChanged();
    partial void OnIv_AVEChanging(float value);
    partial void OnIv_AVEChanged();
    partial void OnIv_STDChanging(float value);
    partial void OnIv_STDChanged();
    partial void OnVl3_MINChanging(float value);
    partial void OnVl3_MINChanged();
    partial void OnVl3_MAXChanging(float value);
    partial void OnVl3_MAXChanged();
    partial void OnVl3_AVEChanging(float value);
    partial void OnVl3_AVEChanged();
    partial void OnVl3_STDChanging(float value);
    partial void OnVl3_STDChanged();
    partial void OnDel_FGChanging(bool value);
    partial void OnDel_FGChanged();
    partial void OnUpdUser_CDChanging(string value);
    partial void OnUpdUser_CDChanged();
    partial void OnLastUpd_DTChanging(System.DateTime value);
    partial void OnLastUpd_DTChanged();
    partial void OnThickness_AVEChanging(float value);
    partial void OnThickness_AVEChanged();
    partial void OnSupply_IDChanging(string value);
    partial void OnSupply_IDChanged();
    partial void OnChipQty_CTChanging(decimal value);
    partial void OnChipQty_CTChanged();
    partial void OnWaveAve_VALChanging(float value);
    partial void OnWaveAve_VALChanged();
    partial void OnWaveStd_VALChanging(float value);
    partial void OnWaveStd_VALChanged();
    partial void OnWaveCpt_NMChanging(string value);
    partial void OnWaveCpt_NMChanged();
    #endregion
		
		public NttDITK()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiceLot_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int DiceLot_ID
		{
			get
			{
				return this._DiceLot_ID;
			}
			set
			{
				if ((this._DiceLot_ID != value))
				{
					this.OnDiceLot_IDChanging(value);
					this.SendPropertyChanging();
					this._DiceLot_ID = value;
					this.SendPropertyChanged("DiceLot_ID");
					this.OnDiceLot_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RootsLot_NO", DbType="VarChar(64) NOT NULL", CanBeNull=false)]
		public string RootsLot_NO
		{
			get
			{
				return this._RootsLot_NO;
			}
			set
			{
				if ((this._RootsLot_NO != value))
				{
					this.OnRootsLot_NOChanging(value);
					this.SendPropertyChanging();
					this._RootsLot_NO = value;
					this.SendPropertyChanged("RootsLot_NO");
					this.OnRootsLot_NOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserLot_NO", DbType="VarChar(64) NOT NULL", CanBeNull=false)]
		public string UserLot_NO
		{
			get
			{
				return this._UserLot_NO;
			}
			set
			{
				if ((this._UserLot_NO != value))
				{
					this.OnUserLot_NOChanging(value);
					this.SendPropertyChanging();
					this._UserLot_NO = value;
					this.SendPropertyChanged("UserLot_NO");
					this.OnUserLot_NOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Material_CD", DbType="Char(24) NOT NULL", CanBeNull=false)]
		public string Material_CD
		{
			get
			{
				return this._Material_CD;
			}
			set
			{
				if ((this._Material_CD != value))
				{
					this.OnMaterial_CDChanging(value);
					this.SendPropertyChanging();
					this._Material_CD = value;
					this.SendPropertyChanged("Material_CD");
					this.OnMaterial_CDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiceSelection_NM", DbType="Char(20) NOT NULL", CanBeNull=false)]
		public string DiceSelection_NM
		{
			get
			{
				return this._DiceSelection_NM;
			}
			set
			{
				if ((this._DiceSelection_NM != value))
				{
					this.OnDiceSelection_NMChanging(value);
					this.SendPropertyChanging();
					this._DiceSelection_NM = value;
					this.SendPropertyChanged("DiceSelection_NM");
					this.OnDiceSelection_NMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiceRank_NM", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string DiceRank_NM
		{
			get
			{
				return this._DiceRank_NM;
			}
			set
			{
				if ((this._DiceRank_NM != value))
				{
					this.OnDiceRank_NMChanging(value);
					this.SendPropertyChanging();
					this._DiceRank_NM = value;
					this.SendPropertyChanged("DiceRank_NM");
					this.OnDiceRank_NMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Inka_NM", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string Inka_NM
		{
			get
			{
				return this._Inka_NM;
			}
			set
			{
				if ((this._Inka_NM != value))
				{
					this.OnInka_NMChanging(value);
					this.SendPropertyChanging();
					this._Inka_NM = value;
					this.SendPropertyChanged("Inka_NM");
					this.OnInka_NMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Wd_MIN", DbType="Real NOT NULL")]
		public float Wd_MIN
		{
			get
			{
				return this._Wd_MIN;
			}
			set
			{
				if ((this._Wd_MIN != value))
				{
					this.OnWd_MINChanging(value);
					this.SendPropertyChanging();
					this._Wd_MIN = value;
					this.SendPropertyChanged("Wd_MIN");
					this.OnWd_MINChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Wd_MAX", DbType="Real NOT NULL")]
		public float Wd_MAX
		{
			get
			{
				return this._Wd_MAX;
			}
			set
			{
				if ((this._Wd_MAX != value))
				{
					this.OnWd_MAXChanging(value);
					this.SendPropertyChanging();
					this._Wd_MAX = value;
					this.SendPropertyChanged("Wd_MAX");
					this.OnWd_MAXChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Wd_AVE", DbType="Real NOT NULL")]
		public float Wd_AVE
		{
			get
			{
				return this._Wd_AVE;
			}
			set
			{
				if ((this._Wd_AVE != value))
				{
					this.OnWd_AVEChanging(value);
					this.SendPropertyChanging();
					this._Wd_AVE = value;
					this.SendPropertyChanged("Wd_AVE");
					this.OnWd_AVEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Wd_STD", DbType="Real NOT NULL")]
		public float Wd_STD
		{
			get
			{
				return this._Wd_STD;
			}
			set
			{
				if ((this._Wd_STD != value))
				{
					this.OnWd_STDChanging(value);
					this.SendPropertyChanging();
					this._Wd_STD = value;
					this.SendPropertyChanged("Wd_STD");
					this.OnWd_STDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Wp_MIN", DbType="Real NOT NULL")]
		public float Wp_MIN
		{
			get
			{
				return this._Wp_MIN;
			}
			set
			{
				if ((this._Wp_MIN != value))
				{
					this.OnWp_MINChanging(value);
					this.SendPropertyChanging();
					this._Wp_MIN = value;
					this.SendPropertyChanged("Wp_MIN");
					this.OnWp_MINChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Wp_MAX", DbType="Real NOT NULL")]
		public float Wp_MAX
		{
			get
			{
				return this._Wp_MAX;
			}
			set
			{
				if ((this._Wp_MAX != value))
				{
					this.OnWp_MAXChanging(value);
					this.SendPropertyChanging();
					this._Wp_MAX = value;
					this.SendPropertyChanged("Wp_MAX");
					this.OnWp_MAXChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Wp_AVE", DbType="Real NOT NULL")]
		public float Wp_AVE
		{
			get
			{
				return this._Wp_AVE;
			}
			set
			{
				if ((this._Wp_AVE != value))
				{
					this.OnWp_AVEChanging(value);
					this.SendPropertyChanging();
					this._Wp_AVE = value;
					this.SendPropertyChanged("Wp_AVE");
					this.OnWp_AVEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Wp_STD", DbType="Real NOT NULL")]
		public float Wp_STD
		{
			get
			{
				return this._Wp_STD;
			}
			set
			{
				if ((this._Wp_STD != value))
				{
					this.OnWp_STDChanging(value);
					this.SendPropertyChanging();
					this._Wp_STD = value;
					this.SendPropertyChanged("Wp_STD");
					this.OnWp_STDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Po_MIN", DbType="Real NOT NULL")]
		public float Po_MIN
		{
			get
			{
				return this._Po_MIN;
			}
			set
			{
				if ((this._Po_MIN != value))
				{
					this.OnPo_MINChanging(value);
					this.SendPropertyChanging();
					this._Po_MIN = value;
					this.SendPropertyChanged("Po_MIN");
					this.OnPo_MINChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Po_MAX", DbType="Real NOT NULL")]
		public float Po_MAX
		{
			get
			{
				return this._Po_MAX;
			}
			set
			{
				if ((this._Po_MAX != value))
				{
					this.OnPo_MAXChanging(value);
					this.SendPropertyChanging();
					this._Po_MAX = value;
					this.SendPropertyChanged("Po_MAX");
					this.OnPo_MAXChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Po_AVE", DbType="Real NOT NULL")]
		public float Po_AVE
		{
			get
			{
				return this._Po_AVE;
			}
			set
			{
				if ((this._Po_AVE != value))
				{
					this.OnPo_AVEChanging(value);
					this.SendPropertyChanging();
					this._Po_AVE = value;
					this.SendPropertyChanged("Po_AVE");
					this.OnPo_AVEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Po_STD", DbType="Real NOT NULL")]
		public float Po_STD
		{
			get
			{
				return this._Po_STD;
			}
			set
			{
				if ((this._Po_STD != value))
				{
					this.OnPo_STDChanging(value);
					this.SendPropertyChanging();
					this._Po_STD = value;
					this.SendPropertyChanged("Po_STD");
					this.OnPo_STDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Vf_MIN", DbType="Real NOT NULL")]
		public float Vf_MIN
		{
			get
			{
				return this._Vf_MIN;
			}
			set
			{
				if ((this._Vf_MIN != value))
				{
					this.OnVf_MINChanging(value);
					this.SendPropertyChanging();
					this._Vf_MIN = value;
					this.SendPropertyChanged("Vf_MIN");
					this.OnVf_MINChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Vf_MAX", DbType="Real NOT NULL")]
		public float Vf_MAX
		{
			get
			{
				return this._Vf_MAX;
			}
			set
			{
				if ((this._Vf_MAX != value))
				{
					this.OnVf_MAXChanging(value);
					this.SendPropertyChanging();
					this._Vf_MAX = value;
					this.SendPropertyChanged("Vf_MAX");
					this.OnVf_MAXChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Vf_AVE", DbType="Real NOT NULL")]
		public float Vf_AVE
		{
			get
			{
				return this._Vf_AVE;
			}
			set
			{
				if ((this._Vf_AVE != value))
				{
					this.OnVf_AVEChanging(value);
					this.SendPropertyChanging();
					this._Vf_AVE = value;
					this.SendPropertyChanged("Vf_AVE");
					this.OnVf_AVEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Vf_STD", DbType="Real NOT NULL")]
		public float Vf_STD
		{
			get
			{
				return this._Vf_STD;
			}
			set
			{
				if ((this._Vf_STD != value))
				{
					this.OnVf_STDChanging(value);
					this.SendPropertyChanging();
					this._Vf_STD = value;
					this.SendPropertyChanged("Vf_STD");
					this.OnVf_STDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Iv_MIN", DbType="Real NOT NULL")]
		public float Iv_MIN
		{
			get
			{
				return this._Iv_MIN;
			}
			set
			{
				if ((this._Iv_MIN != value))
				{
					this.OnIv_MINChanging(value);
					this.SendPropertyChanging();
					this._Iv_MIN = value;
					this.SendPropertyChanged("Iv_MIN");
					this.OnIv_MINChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Iv_MAX", DbType="Real NOT NULL")]
		public float Iv_MAX
		{
			get
			{
				return this._Iv_MAX;
			}
			set
			{
				if ((this._Iv_MAX != value))
				{
					this.OnIv_MAXChanging(value);
					this.SendPropertyChanging();
					this._Iv_MAX = value;
					this.SendPropertyChanged("Iv_MAX");
					this.OnIv_MAXChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Iv_AVE", DbType="Real NOT NULL")]
		public float Iv_AVE
		{
			get
			{
				return this._Iv_AVE;
			}
			set
			{
				if ((this._Iv_AVE != value))
				{
					this.OnIv_AVEChanging(value);
					this.SendPropertyChanging();
					this._Iv_AVE = value;
					this.SendPropertyChanged("Iv_AVE");
					this.OnIv_AVEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Iv_STD", DbType="Real NOT NULL")]
		public float Iv_STD
		{
			get
			{
				return this._Iv_STD;
			}
			set
			{
				if ((this._Iv_STD != value))
				{
					this.OnIv_STDChanging(value);
					this.SendPropertyChanging();
					this._Iv_STD = value;
					this.SendPropertyChanged("Iv_STD");
					this.OnIv_STDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Vl3_MIN", DbType="Real NOT NULL")]
		public float Vl3_MIN
		{
			get
			{
				return this._Vl3_MIN;
			}
			set
			{
				if ((this._Vl3_MIN != value))
				{
					this.OnVl3_MINChanging(value);
					this.SendPropertyChanging();
					this._Vl3_MIN = value;
					this.SendPropertyChanged("Vl3_MIN");
					this.OnVl3_MINChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Vl3_MAX", DbType="Real NOT NULL")]
		public float Vl3_MAX
		{
			get
			{
				return this._Vl3_MAX;
			}
			set
			{
				if ((this._Vl3_MAX != value))
				{
					this.OnVl3_MAXChanging(value);
					this.SendPropertyChanging();
					this._Vl3_MAX = value;
					this.SendPropertyChanged("Vl3_MAX");
					this.OnVl3_MAXChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Vl3_AVE", DbType="Real NOT NULL")]
		public float Vl3_AVE
		{
			get
			{
				return this._Vl3_AVE;
			}
			set
			{
				if ((this._Vl3_AVE != value))
				{
					this.OnVl3_AVEChanging(value);
					this.SendPropertyChanging();
					this._Vl3_AVE = value;
					this.SendPropertyChanged("Vl3_AVE");
					this.OnVl3_AVEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Vl3_STD", DbType="Real NOT NULL")]
		public float Vl3_STD
		{
			get
			{
				return this._Vl3_STD;
			}
			set
			{
				if ((this._Vl3_STD != value))
				{
					this.OnVl3_STDChanging(value);
					this.SendPropertyChanging();
					this._Vl3_STD = value;
					this.SendPropertyChanged("Vl3_STD");
					this.OnVl3_STDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Del_FG", DbType="Bit NOT NULL")]
		public bool Del_FG
		{
			get
			{
				return this._Del_FG;
			}
			set
			{
				if ((this._Del_FG != value))
				{
					this.OnDel_FGChanging(value);
					this.SendPropertyChanging();
					this._Del_FG = value;
					this.SendPropertyChanged("Del_FG");
					this.OnDel_FGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdUser_CD", DbType="Char(8) NOT NULL", CanBeNull=false)]
		public string UpdUser_CD
		{
			get
			{
				return this._UpdUser_CD;
			}
			set
			{
				if ((this._UpdUser_CD != value))
				{
					this.OnUpdUser_CDChanging(value);
					this.SendPropertyChanging();
					this._UpdUser_CD = value;
					this.SendPropertyChanged("UpdUser_CD");
					this.OnUpdUser_CDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastUpd_DT", DbType="DateTime NOT NULL")]
		public System.DateTime LastUpd_DT
		{
			get
			{
				return this._LastUpd_DT;
			}
			set
			{
				if ((this._LastUpd_DT != value))
				{
					this.OnLastUpd_DTChanging(value);
					this.SendPropertyChanging();
					this._LastUpd_DT = value;
					this.SendPropertyChanged("LastUpd_DT");
					this.OnLastUpd_DTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Thickness_AVE", DbType="Real NOT NULL")]
		public float Thickness_AVE
		{
			get
			{
				return this._Thickness_AVE;
			}
			set
			{
				if ((this._Thickness_AVE != value))
				{
					this.OnThickness_AVEChanging(value);
					this.SendPropertyChanging();
					this._Thickness_AVE = value;
					this.SendPropertyChanged("Thickness_AVE");
					this.OnThickness_AVEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Supply_ID", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string Supply_ID
		{
			get
			{
				return this._Supply_ID;
			}
			set
			{
				if ((this._Supply_ID != value))
				{
					this.OnSupply_IDChanging(value);
					this.SendPropertyChanging();
					this._Supply_ID = value;
					this.SendPropertyChanged("Supply_ID");
					this.OnSupply_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChipQty_CT", DbType="Decimal(15,3) NOT NULL")]
		public decimal ChipQty_CT
		{
			get
			{
				return this._ChipQty_CT;
			}
			set
			{
				if ((this._ChipQty_CT != value))
				{
					this.OnChipQty_CTChanging(value);
					this.SendPropertyChanging();
					this._ChipQty_CT = value;
					this.SendPropertyChanged("ChipQty_CT");
					this.OnChipQty_CTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WaveAve_VAL", DbType="Real NOT NULL")]
		public float WaveAve_VAL
		{
			get
			{
				return this._WaveAve_VAL;
			}
			set
			{
				if ((this._WaveAve_VAL != value))
				{
					this.OnWaveAve_VALChanging(value);
					this.SendPropertyChanging();
					this._WaveAve_VAL = value;
					this.SendPropertyChanged("WaveAve_VAL");
					this.OnWaveAve_VALChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WaveStd_VAL", DbType="Real NOT NULL")]
		public float WaveStd_VAL
		{
			get
			{
				return this._WaveStd_VAL;
			}
			set
			{
				if ((this._WaveStd_VAL != value))
				{
					this.OnWaveStd_VALChanging(value);
					this.SendPropertyChanging();
					this._WaveStd_VAL = value;
					this.SendPropertyChanged("WaveStd_VAL");
					this.OnWaveStd_VALChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WaveCpt_NM", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string WaveCpt_NM
		{
			get
			{
				return this._WaveCpt_NM;
			}
			set
			{
				if ((this._WaveCpt_NM != value))
				{
					this.OnWaveCpt_NMChanging(value);
					this.SendPropertyChanging();
					this._WaveCpt_NM = value;
					this.SendPropertyChanged("WaveCpt_NM");
					this.OnWaveCpt_NMChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NttRING")]
	public partial class NttRING : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Ring_Num;
		
		private string _Ring_ID;
		
		private string _Material_CD;
		
		private string _RootsLot_NO;
		
		private System.DateTime _Assign_DT;
		
		private string _Assign_Usr_CD;
		
		private bool _Del_FG;
		
		private string _UpdUser_CD;
		
		private System.DateTime _LastUpd_DT;
		
    #region 拡張メソッドの定義
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnRing_NumChanging(int value);
    partial void OnRing_NumChanged();
    partial void OnRing_IDChanging(string value);
    partial void OnRing_IDChanged();
    partial void OnMaterial_CDChanging(string value);
    partial void OnMaterial_CDChanged();
    partial void OnRootsLot_NOChanging(string value);
    partial void OnRootsLot_NOChanged();
    partial void OnAssign_DTChanging(System.DateTime value);
    partial void OnAssign_DTChanged();
    partial void OnAssign_Usr_CDChanging(string value);
    partial void OnAssign_Usr_CDChanged();
    partial void OnDel_FGChanging(bool value);
    partial void OnDel_FGChanged();
    partial void OnUpdUser_CDChanging(string value);
    partial void OnUpdUser_CDChanged();
    partial void OnLastUpd_DTChanging(System.DateTime value);
    partial void OnLastUpd_DTChanged();
    #endregion
		
		public NttRING()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ring_Num", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Ring_Num
		{
			get
			{
				return this._Ring_Num;
			}
			set
			{
				if ((this._Ring_Num != value))
				{
					this.OnRing_NumChanging(value);
					this.SendPropertyChanging();
					this._Ring_Num = value;
					this.SendPropertyChanged("Ring_Num");
					this.OnRing_NumChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ring_ID", DbType="NVarChar(24) NOT NULL", CanBeNull=false)]
		public string Ring_ID
		{
			get
			{
				return this._Ring_ID;
			}
			set
			{
				if ((this._Ring_ID != value))
				{
					this.OnRing_IDChanging(value);
					this.SendPropertyChanging();
					this._Ring_ID = value;
					this.SendPropertyChanged("Ring_ID");
					this.OnRing_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Material_CD", DbType="Char(24) NOT NULL", CanBeNull=false)]
		public string Material_CD
		{
			get
			{
				return this._Material_CD;
			}
			set
			{
				if ((this._Material_CD != value))
				{
					this.OnMaterial_CDChanging(value);
					this.SendPropertyChanging();
					this._Material_CD = value;
					this.SendPropertyChanged("Material_CD");
					this.OnMaterial_CDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RootsLot_NO", DbType="VarChar(64) NOT NULL", CanBeNull=false)]
		public string RootsLot_NO
		{
			get
			{
				return this._RootsLot_NO;
			}
			set
			{
				if ((this._RootsLot_NO != value))
				{
					this.OnRootsLot_NOChanging(value);
					this.SendPropertyChanging();
					this._RootsLot_NO = value;
					this.SendPropertyChanged("RootsLot_NO");
					this.OnRootsLot_NOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Assign_DT", DbType="DateTime NOT NULL")]
		public System.DateTime Assign_DT
		{
			get
			{
				return this._Assign_DT;
			}
			set
			{
				if ((this._Assign_DT != value))
				{
					this.OnAssign_DTChanging(value);
					this.SendPropertyChanging();
					this._Assign_DT = value;
					this.SendPropertyChanged("Assign_DT");
					this.OnAssign_DTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Assign_Usr_CD", DbType="Char(8) NOT NULL", CanBeNull=false)]
		public string Assign_Usr_CD
		{
			get
			{
				return this._Assign_Usr_CD;
			}
			set
			{
				if ((this._Assign_Usr_CD != value))
				{
					this.OnAssign_Usr_CDChanging(value);
					this.SendPropertyChanging();
					this._Assign_Usr_CD = value;
					this.SendPropertyChanged("Assign_Usr_CD");
					this.OnAssign_Usr_CDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Del_FG", DbType="Bit NOT NULL")]
		public bool Del_FG
		{
			get
			{
				return this._Del_FG;
			}
			set
			{
				if ((this._Del_FG != value))
				{
					this.OnDel_FGChanging(value);
					this.SendPropertyChanging();
					this._Del_FG = value;
					this.SendPropertyChanged("Del_FG");
					this.OnDel_FGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdUser_CD", DbType="Char(8) NOT NULL", CanBeNull=false)]
		public string UpdUser_CD
		{
			get
			{
				return this._UpdUser_CD;
			}
			set
			{
				if ((this._UpdUser_CD != value))
				{
					this.OnUpdUser_CDChanging(value);
					this.SendPropertyChanging();
					this._UpdUser_CD = value;
					this.SendPropertyChanged("UpdUser_CD");
					this.OnUpdUser_CDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastUpd_DT", DbType="DateTime NOT NULL")]
		public System.DateTime LastUpd_DT
		{
			get
			{
				return this._LastUpd_DT;
			}
			set
			{
				if ((this._LastUpd_DT != value))
				{
					this.OnLastUpd_DTChanging(value);
					this.SendPropertyChanging();
					this._LastUpd_DT = value;
					this.SendPropertyChanged("LastUpd_DT");
					this.OnLastUpd_DTChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
