#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArmsApi.Model.DataContext
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="NJDB02")]
	public partial class NJDBDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region 拡張メソッドの定義
    partial void OnCreated();
    partial void InsertJtmMIXRATEMAT(JtmMIXRATEMAT instance);
    partial void UpdateJtmMIXRATEMAT(JtmMIXRATEMAT instance);
    partial void DeleteJtmMIXRATEMAT(JtmMIXRATEMAT instance);
    partial void InsertJttMIXRESULTLOT(JttMIXRESULTLOT instance);
    partial void UpdateJttMIXRESULTLOT(JttMIXRESULTLOT instance);
    partial void DeleteJttMIXRESULTLOT(JttMIXRESULTLOT instance);
    partial void InsertJttMIXRESULT(JttMIXRESULT instance);
    partial void UpdateJttMIXRESULT(JttMIXRESULT instance);
    partial void DeleteJttMIXRESULT(JttMIXRESULT instance);
    partial void InsertJtmMAT(JtmMAT instance);
    partial void UpdateJtmMAT(JtmMAT instance);
    partial void DeleteJtmMAT(JtmMAT instance);
    partial void InsertJtmMATCONV(JtmMATCONV instance);
    partial void UpdateJtmMATCONV(JtmMATCONV instance);
    partial void DeleteJtmMATCONV(JtmMATCONV instance);
    #endregion
		
		public NJDBDataContext() : 
				base(global::ArmsApi.Properties.Settings.Default.NJDB02ConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public NJDBDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public NJDBDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public NJDBDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public NJDBDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<JtmMIXRATEMAT> JtmMIXRATEMAT
		{
			get
			{
				return this.GetTable<JtmMIXRATEMAT>();
			}
		}
		
		public System.Data.Linq.Table<JttMIXRESULTLOT> JttMIXRESULTLOT
		{
			get
			{
				return this.GetTable<JttMIXRESULTLOT>();
			}
		}
		
		public System.Data.Linq.Table<JttMIXRESULT> JttMIXRESULT
		{
			get
			{
				return this.GetTable<JttMIXRESULT>();
			}
		}
		
		public System.Data.Linq.Table<JtmMAT> JtmMAT
		{
			get
			{
				return this.GetTable<JtmMAT>();
			}
		}
		
		public System.Data.Linq.Table<JtmMATCONV> JtmMATCONV
		{
			get
			{
				return this.GetTable<JtmMATCONV>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.JtmMIXRATEMAT")]
	public partial class JtmMIXRATEMAT : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _MixRate_ID;
		
		private int _MateLin_NO;
		
		private string _Material_CD;
		
		private System.Nullable<decimal> _MixRate_VAL;
		
		private System.Nullable<decimal> _MixError_VAL;
		
		private System.Nullable<int> _MaxFreeze_VAL;
		
		private System.Nullable<int> _OpenValidity_DAY;
		
		private System.Nullable<bool> _Identity_FG;
		
		private string _ChkMaterial_CD;
		
		private string _ChkLot_NO;
		
		private System.Nullable<decimal> _YagTranX_VAL;
		
		private System.Nullable<decimal> _YagWeightX_VAL;
		
		private System.Nullable<decimal> _YagTranY_VAL;
		
		private System.Nullable<decimal> _YagWeightY_VAL;
		
		private System.Nullable<bool> _YagMix_FG;
		
		private System.Nullable<bool> _Lock;
		
    #region 拡張メソッドの定義
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMixRate_IDChanging(long value);
    partial void OnMixRate_IDChanged();
    partial void OnMateLin_NOChanging(int value);
    partial void OnMateLin_NOChanged();
    partial void OnMaterial_CDChanging(string value);
    partial void OnMaterial_CDChanged();
    partial void OnMixRate_VALChanging(System.Nullable<decimal> value);
    partial void OnMixRate_VALChanged();
    partial void OnMixError_VALChanging(System.Nullable<decimal> value);
    partial void OnMixError_VALChanged();
    partial void OnMaxFreeze_VALChanging(System.Nullable<int> value);
    partial void OnMaxFreeze_VALChanged();
    partial void OnOpenValidity_DAYChanging(System.Nullable<int> value);
    partial void OnOpenValidity_DAYChanged();
    partial void OnIdentity_FGChanging(System.Nullable<bool> value);
    partial void OnIdentity_FGChanged();
    partial void OnChkMaterial_CDChanging(string value);
    partial void OnChkMaterial_CDChanged();
    partial void OnChkLot_NOChanging(string value);
    partial void OnChkLot_NOChanged();
    partial void OnYagTranX_VALChanging(System.Nullable<decimal> value);
    partial void OnYagTranX_VALChanged();
    partial void OnYagWeightX_VALChanging(System.Nullable<decimal> value);
    partial void OnYagWeightX_VALChanged();
    partial void OnYagTranY_VALChanging(System.Nullable<decimal> value);
    partial void OnYagTranY_VALChanged();
    partial void OnYagWeightY_VALChanging(System.Nullable<decimal> value);
    partial void OnYagWeightY_VALChanged();
    partial void OnYagMix_FGChanging(System.Nullable<bool> value);
    partial void OnYagMix_FGChanged();
    partial void OnLockChanging(System.Nullable<bool> value);
    partial void OnLockChanged();
    #endregion
		
		public JtmMIXRATEMAT()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MixRate_ID", DbType="BigInt NOT NULL", IsPrimaryKey=true)]
		public long MixRate_ID
		{
			get
			{
				return this._MixRate_ID;
			}
			set
			{
				if ((this._MixRate_ID != value))
				{
					this.OnMixRate_IDChanging(value);
					this.SendPropertyChanging();
					this._MixRate_ID = value;
					this.SendPropertyChanged("MixRate_ID");
					this.OnMixRate_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MateLin_NO", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MateLin_NO
		{
			get
			{
				return this._MateLin_NO;
			}
			set
			{
				if ((this._MateLin_NO != value))
				{
					this.OnMateLin_NOChanging(value);
					this.SendPropertyChanging();
					this._MateLin_NO = value;
					this.SendPropertyChanged("MateLin_NO");
					this.OnMateLin_NOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Material_CD", DbType="Char(24)")]
		public string Material_CD
		{
			get
			{
				return this._Material_CD;
			}
			set
			{
				if ((this._Material_CD != value))
				{
					this.OnMaterial_CDChanging(value);
					this.SendPropertyChanging();
					this._Material_CD = value;
					this.SendPropertyChanged("Material_CD");
					this.OnMaterial_CDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MixRate_VAL", DbType="Decimal(10,4)")]
		public System.Nullable<decimal> MixRate_VAL
		{
			get
			{
				return this._MixRate_VAL;
			}
			set
			{
				if ((this._MixRate_VAL != value))
				{
					this.OnMixRate_VALChanging(value);
					this.SendPropertyChanging();
					this._MixRate_VAL = value;
					this.SendPropertyChanged("MixRate_VAL");
					this.OnMixRate_VALChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MixError_VAL", DbType="Decimal(10,4)")]
		public System.Nullable<decimal> MixError_VAL
		{
			get
			{
				return this._MixError_VAL;
			}
			set
			{
				if ((this._MixError_VAL != value))
				{
					this.OnMixError_VALChanging(value);
					this.SendPropertyChanging();
					this._MixError_VAL = value;
					this.SendPropertyChanged("MixError_VAL");
					this.OnMixError_VALChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaxFreeze_VAL", DbType="Int")]
		public System.Nullable<int> MaxFreeze_VAL
		{
			get
			{
				return this._MaxFreeze_VAL;
			}
			set
			{
				if ((this._MaxFreeze_VAL != value))
				{
					this.OnMaxFreeze_VALChanging(value);
					this.SendPropertyChanging();
					this._MaxFreeze_VAL = value;
					this.SendPropertyChanged("MaxFreeze_VAL");
					this.OnMaxFreeze_VALChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OpenValidity_DAY", DbType="Int")]
		public System.Nullable<int> OpenValidity_DAY
		{
			get
			{
				return this._OpenValidity_DAY;
			}
			set
			{
				if ((this._OpenValidity_DAY != value))
				{
					this.OnOpenValidity_DAYChanging(value);
					this.SendPropertyChanging();
					this._OpenValidity_DAY = value;
					this.SendPropertyChanged("OpenValidity_DAY");
					this.OnOpenValidity_DAYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Identity_FG", DbType="Bit")]
		public System.Nullable<bool> Identity_FG
		{
			get
			{
				return this._Identity_FG;
			}
			set
			{
				if ((this._Identity_FG != value))
				{
					this.OnIdentity_FGChanging(value);
					this.SendPropertyChanging();
					this._Identity_FG = value;
					this.SendPropertyChanged("Identity_FG");
					this.OnIdentity_FGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChkMaterial_CD", DbType="Char(24)")]
		public string ChkMaterial_CD
		{
			get
			{
				return this._ChkMaterial_CD;
			}
			set
			{
				if ((this._ChkMaterial_CD != value))
				{
					this.OnChkMaterial_CDChanging(value);
					this.SendPropertyChanging();
					this._ChkMaterial_CD = value;
					this.SendPropertyChanged("ChkMaterial_CD");
					this.OnChkMaterial_CDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChkLot_NO", DbType="VarChar(64)")]
		public string ChkLot_NO
		{
			get
			{
				return this._ChkLot_NO;
			}
			set
			{
				if ((this._ChkLot_NO != value))
				{
					this.OnChkLot_NOChanging(value);
					this.SendPropertyChanging();
					this._ChkLot_NO = value;
					this.SendPropertyChanged("ChkLot_NO");
					this.OnChkLot_NOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YagTranX_VAL", DbType="Decimal(10,4)")]
		public System.Nullable<decimal> YagTranX_VAL
		{
			get
			{
				return this._YagTranX_VAL;
			}
			set
			{
				if ((this._YagTranX_VAL != value))
				{
					this.OnYagTranX_VALChanging(value);
					this.SendPropertyChanging();
					this._YagTranX_VAL = value;
					this.SendPropertyChanged("YagTranX_VAL");
					this.OnYagTranX_VALChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YagWeightX_VAL", DbType="Decimal(10,4)")]
		public System.Nullable<decimal> YagWeightX_VAL
		{
			get
			{
				return this._YagWeightX_VAL;
			}
			set
			{
				if ((this._YagWeightX_VAL != value))
				{
					this.OnYagWeightX_VALChanging(value);
					this.SendPropertyChanging();
					this._YagWeightX_VAL = value;
					this.SendPropertyChanged("YagWeightX_VAL");
					this.OnYagWeightX_VALChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YagTranY_VAL", DbType="Decimal(10,4)")]
		public System.Nullable<decimal> YagTranY_VAL
		{
			get
			{
				return this._YagTranY_VAL;
			}
			set
			{
				if ((this._YagTranY_VAL != value))
				{
					this.OnYagTranY_VALChanging(value);
					this.SendPropertyChanging();
					this._YagTranY_VAL = value;
					this.SendPropertyChanged("YagTranY_VAL");
					this.OnYagTranY_VALChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YagWeightY_VAL", DbType="Decimal(10,4)")]
		public System.Nullable<decimal> YagWeightY_VAL
		{
			get
			{
				return this._YagWeightY_VAL;
			}
			set
			{
				if ((this._YagWeightY_VAL != value))
				{
					this.OnYagWeightY_VALChanging(value);
					this.SendPropertyChanging();
					this._YagWeightY_VAL = value;
					this.SendPropertyChanged("YagWeightY_VAL");
					this.OnYagWeightY_VALChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YagMix_FG", DbType="Bit")]
		public System.Nullable<bool> YagMix_FG
		{
			get
			{
				return this._YagMix_FG;
			}
			set
			{
				if ((this._YagMix_FG != value))
				{
					this.OnYagMix_FGChanging(value);
					this.SendPropertyChanging();
					this._YagMix_FG = value;
					this.SendPropertyChanged("YagMix_FG");
					this.OnYagMix_FGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Lock", DbType="Bit")]
		public System.Nullable<bool> Lock
		{
			get
			{
				return this._Lock;
			}
			set
			{
				if ((this._Lock != value))
				{
					this.OnLockChanging(value);
					this.SendPropertyChanging();
					this._Lock = value;
					this.SendPropertyChanged("Lock");
					this.OnLockChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.JttMIXRESULTLOT")]
	public partial class JttMIXRESULTLOT : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _MixResult_ID;
		
		private int _LotLin_NO;
		
		private string _Lot_NO;
		
		private System.Nullable<decimal> _Preset_VAL;
		
		private System.Nullable<decimal> _Measure_VAL;
		
		private long _ParentMixResult_ID;
		
    #region 拡張メソッドの定義
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMixResult_IDChanging(long value);
    partial void OnMixResult_IDChanged();
    partial void OnLotLin_NOChanging(int value);
    partial void OnLotLin_NOChanged();
    partial void OnLot_NOChanging(string value);
    partial void OnLot_NOChanged();
    partial void OnPreset_VALChanging(System.Nullable<decimal> value);
    partial void OnPreset_VALChanged();
    partial void OnMeasure_VALChanging(System.Nullable<decimal> value);
    partial void OnMeasure_VALChanged();
    partial void OnParentMixResult_IDChanging(long value);
    partial void OnParentMixResult_IDChanged();
    #endregion
		
		public JttMIXRESULTLOT()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MixResult_ID", DbType="BigInt NOT NULL", IsPrimaryKey=true)]
		public long MixResult_ID
		{
			get
			{
				return this._MixResult_ID;
			}
			set
			{
				if ((this._MixResult_ID != value))
				{
					this.OnMixResult_IDChanging(value);
					this.SendPropertyChanging();
					this._MixResult_ID = value;
					this.SendPropertyChanged("MixResult_ID");
					this.OnMixResult_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LotLin_NO", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int LotLin_NO
		{
			get
			{
				return this._LotLin_NO;
			}
			set
			{
				if ((this._LotLin_NO != value))
				{
					this.OnLotLin_NOChanging(value);
					this.SendPropertyChanging();
					this._LotLin_NO = value;
					this.SendPropertyChanged("LotLin_NO");
					this.OnLotLin_NOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Lot_NO", DbType="VarChar(64)")]
		public string Lot_NO
		{
			get
			{
				return this._Lot_NO;
			}
			set
			{
				if ((this._Lot_NO != value))
				{
					this.OnLot_NOChanging(value);
					this.SendPropertyChanging();
					this._Lot_NO = value;
					this.SendPropertyChanged("Lot_NO");
					this.OnLot_NOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Preset_VAL", DbType="Decimal(10,4)")]
		public System.Nullable<decimal> Preset_VAL
		{
			get
			{
				return this._Preset_VAL;
			}
			set
			{
				if ((this._Preset_VAL != value))
				{
					this.OnPreset_VALChanging(value);
					this.SendPropertyChanging();
					this._Preset_VAL = value;
					this.SendPropertyChanged("Preset_VAL");
					this.OnPreset_VALChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Measure_VAL", DbType="Decimal(10,4)")]
		public System.Nullable<decimal> Measure_VAL
		{
			get
			{
				return this._Measure_VAL;
			}
			set
			{
				if ((this._Measure_VAL != value))
				{
					this.OnMeasure_VALChanging(value);
					this.SendPropertyChanging();
					this._Measure_VAL = value;
					this.SendPropertyChanged("Measure_VAL");
					this.OnMeasure_VALChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ParentMixResult_ID", DbType="BigInt NOT NULL")]
		public long ParentMixResult_ID
		{
			get
			{
				return this._ParentMixResult_ID;
			}
			set
			{
				if ((this._ParentMixResult_ID != value))
				{
					this.OnParentMixResult_IDChanging(value);
					this.SendPropertyChanging();
					this._ParentMixResult_ID = value;
					this.SendPropertyChanged("ParentMixResult_ID");
					this.OnParentMixResult_IDChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.JttMIXRESULT")]
	public partial class JttMIXRESULT : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _MixResult_ID;
		
		private System.Nullable<int> _MixRate_ID;
		
		private System.Nullable<System.DateTime> _Mixture_DT;
		
		private System.Nullable<int> _Lot_CT;
		
		private System.Nullable<int> _Machine_CT;
		
		private System.Nullable<System.DateTime> _Start_DT;
		
		private System.Nullable<System.DateTime> _End_DT;
		
		private string _MixRate_VAL;
		
		private System.Nullable<decimal> _Alumina_VAL;
		
		private System.Nullable<bool> _Alumina_FG;
		
		private System.Nullable<bool> _Npurge_FG;
		
		private System.Nullable<bool> _Agitate_FG;
		
		private string _Container_NO;
		
		private System.Nullable<decimal> _TotalWeight_VAL;
		
		private System.Nullable<bool> _Scrap_FG;
		
		private string _UpdUser_CD;
		
		private System.Nullable<System.DateTime> _LastUpd_DT;
		
		private System.Nullable<long> _ParentsResultID;
		
    #region 拡張メソッドの定義
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMixResult_IDChanging(long value);
    partial void OnMixResult_IDChanged();
    partial void OnMixRate_IDChanging(System.Nullable<int> value);
    partial void OnMixRate_IDChanged();
    partial void OnMixture_DTChanging(System.Nullable<System.DateTime> value);
    partial void OnMixture_DTChanged();
    partial void OnLot_CTChanging(System.Nullable<int> value);
    partial void OnLot_CTChanged();
    partial void OnMachine_CTChanging(System.Nullable<int> value);
    partial void OnMachine_CTChanged();
    partial void OnStart_DTChanging(System.Nullable<System.DateTime> value);
    partial void OnStart_DTChanged();
    partial void OnEnd_DTChanging(System.Nullable<System.DateTime> value);
    partial void OnEnd_DTChanged();
    partial void OnMixRate_VALChanging(string value);
    partial void OnMixRate_VALChanged();
    partial void OnAlumina_VALChanging(System.Nullable<decimal> value);
    partial void OnAlumina_VALChanged();
    partial void OnAlumina_FGChanging(System.Nullable<bool> value);
    partial void OnAlumina_FGChanged();
    partial void OnNpurge_FGChanging(System.Nullable<bool> value);
    partial void OnNpurge_FGChanged();
    partial void OnAgitate_FGChanging(System.Nullable<bool> value);
    partial void OnAgitate_FGChanged();
    partial void OnContainer_NOChanging(string value);
    partial void OnContainer_NOChanged();
    partial void OnTotalWeight_VALChanging(System.Nullable<decimal> value);
    partial void OnTotalWeight_VALChanged();
    partial void OnScrap_FGChanging(System.Nullable<bool> value);
    partial void OnScrap_FGChanged();
    partial void OnUpdUser_CDChanging(string value);
    partial void OnUpdUser_CDChanged();
    partial void OnLastUpd_DTChanging(System.Nullable<System.DateTime> value);
    partial void OnLastUpd_DTChanged();
    partial void OnParentsResultIDChanging(System.Nullable<long> value);
    partial void OnParentsResultIDChanged();
    #endregion
		
		public JttMIXRESULT()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MixResult_ID", DbType="BigInt NOT NULL", IsPrimaryKey=true)]
		public long MixResult_ID
		{
			get
			{
				return this._MixResult_ID;
			}
			set
			{
				if ((this._MixResult_ID != value))
				{
					this.OnMixResult_IDChanging(value);
					this.SendPropertyChanging();
					this._MixResult_ID = value;
					this.SendPropertyChanged("MixResult_ID");
					this.OnMixResult_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MixRate_ID", DbType="Int")]
		public System.Nullable<int> MixRate_ID
		{
			get
			{
				return this._MixRate_ID;
			}
			set
			{
				if ((this._MixRate_ID != value))
				{
					this.OnMixRate_IDChanging(value);
					this.SendPropertyChanging();
					this._MixRate_ID = value;
					this.SendPropertyChanged("MixRate_ID");
					this.OnMixRate_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mixture_DT", DbType="DateTime")]
		public System.Nullable<System.DateTime> Mixture_DT
		{
			get
			{
				return this._Mixture_DT;
			}
			set
			{
				if ((this._Mixture_DT != value))
				{
					this.OnMixture_DTChanging(value);
					this.SendPropertyChanging();
					this._Mixture_DT = value;
					this.SendPropertyChanged("Mixture_DT");
					this.OnMixture_DTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Lot_CT", DbType="Int")]
		public System.Nullable<int> Lot_CT
		{
			get
			{
				return this._Lot_CT;
			}
			set
			{
				if ((this._Lot_CT != value))
				{
					this.OnLot_CTChanging(value);
					this.SendPropertyChanging();
					this._Lot_CT = value;
					this.SendPropertyChanged("Lot_CT");
					this.OnLot_CTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Machine_CT", DbType="Int")]
		public System.Nullable<int> Machine_CT
		{
			get
			{
				return this._Machine_CT;
			}
			set
			{
				if ((this._Machine_CT != value))
				{
					this.OnMachine_CTChanging(value);
					this.SendPropertyChanging();
					this._Machine_CT = value;
					this.SendPropertyChanged("Machine_CT");
					this.OnMachine_CTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Start_DT", DbType="DateTime")]
		public System.Nullable<System.DateTime> Start_DT
		{
			get
			{
				return this._Start_DT;
			}
			set
			{
				if ((this._Start_DT != value))
				{
					this.OnStart_DTChanging(value);
					this.SendPropertyChanging();
					this._Start_DT = value;
					this.SendPropertyChanged("Start_DT");
					this.OnStart_DTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_End_DT", DbType="DateTime")]
		public System.Nullable<System.DateTime> End_DT
		{
			get
			{
				return this._End_DT;
			}
			set
			{
				if ((this._End_DT != value))
				{
					this.OnEnd_DTChanging(value);
					this.SendPropertyChanging();
					this._End_DT = value;
					this.SendPropertyChanged("End_DT");
					this.OnEnd_DTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MixRate_VAL", DbType="VarChar(50)")]
		public string MixRate_VAL
		{
			get
			{
				return this._MixRate_VAL;
			}
			set
			{
				if ((this._MixRate_VAL != value))
				{
					this.OnMixRate_VALChanging(value);
					this.SendPropertyChanging();
					this._MixRate_VAL = value;
					this.SendPropertyChanged("MixRate_VAL");
					this.OnMixRate_VALChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Alumina_VAL", DbType="Decimal(18,4)")]
		public System.Nullable<decimal> Alumina_VAL
		{
			get
			{
				return this._Alumina_VAL;
			}
			set
			{
				if ((this._Alumina_VAL != value))
				{
					this.OnAlumina_VALChanging(value);
					this.SendPropertyChanging();
					this._Alumina_VAL = value;
					this.SendPropertyChanged("Alumina_VAL");
					this.OnAlumina_VALChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Alumina_FG", DbType="Bit")]
		public System.Nullable<bool> Alumina_FG
		{
			get
			{
				return this._Alumina_FG;
			}
			set
			{
				if ((this._Alumina_FG != value))
				{
					this.OnAlumina_FGChanging(value);
					this.SendPropertyChanging();
					this._Alumina_FG = value;
					this.SendPropertyChanged("Alumina_FG");
					this.OnAlumina_FGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Npurge_FG", DbType="Bit")]
		public System.Nullable<bool> Npurge_FG
		{
			get
			{
				return this._Npurge_FG;
			}
			set
			{
				if ((this._Npurge_FG != value))
				{
					this.OnNpurge_FGChanging(value);
					this.SendPropertyChanging();
					this._Npurge_FG = value;
					this.SendPropertyChanged("Npurge_FG");
					this.OnNpurge_FGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Agitate_FG", DbType="Bit")]
		public System.Nullable<bool> Agitate_FG
		{
			get
			{
				return this._Agitate_FG;
			}
			set
			{
				if ((this._Agitate_FG != value))
				{
					this.OnAgitate_FGChanging(value);
					this.SendPropertyChanging();
					this._Agitate_FG = value;
					this.SendPropertyChanged("Agitate_FG");
					this.OnAgitate_FGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Container_NO", DbType="VarChar(15)")]
		public string Container_NO
		{
			get
			{
				return this._Container_NO;
			}
			set
			{
				if ((this._Container_NO != value))
				{
					this.OnContainer_NOChanging(value);
					this.SendPropertyChanging();
					this._Container_NO = value;
					this.SendPropertyChanged("Container_NO");
					this.OnContainer_NOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TotalWeight_VAL", DbType="Decimal(18,4)")]
		public System.Nullable<decimal> TotalWeight_VAL
		{
			get
			{
				return this._TotalWeight_VAL;
			}
			set
			{
				if ((this._TotalWeight_VAL != value))
				{
					this.OnTotalWeight_VALChanging(value);
					this.SendPropertyChanging();
					this._TotalWeight_VAL = value;
					this.SendPropertyChanged("TotalWeight_VAL");
					this.OnTotalWeight_VALChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Scrap_FG", DbType="Bit")]
		public System.Nullable<bool> Scrap_FG
		{
			get
			{
				return this._Scrap_FG;
			}
			set
			{
				if ((this._Scrap_FG != value))
				{
					this.OnScrap_FGChanging(value);
					this.SendPropertyChanging();
					this._Scrap_FG = value;
					this.SendPropertyChanged("Scrap_FG");
					this.OnScrap_FGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdUser_CD", DbType="Char(8)")]
		public string UpdUser_CD
		{
			get
			{
				return this._UpdUser_CD;
			}
			set
			{
				if ((this._UpdUser_CD != value))
				{
					this.OnUpdUser_CDChanging(value);
					this.SendPropertyChanging();
					this._UpdUser_CD = value;
					this.SendPropertyChanged("UpdUser_CD");
					this.OnUpdUser_CDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastUpd_DT", DbType="DateTime")]
		public System.Nullable<System.DateTime> LastUpd_DT
		{
			get
			{
				return this._LastUpd_DT;
			}
			set
			{
				if ((this._LastUpd_DT != value))
				{
					this.OnLastUpd_DTChanging(value);
					this.SendPropertyChanging();
					this._LastUpd_DT = value;
					this.SendPropertyChanged("LastUpd_DT");
					this.OnLastUpd_DTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ParentsResultID", DbType="BigInt")]
		public System.Nullable<long> ParentsResultID
		{
			get
			{
				return this._ParentsResultID;
			}
			set
			{
				if ((this._ParentsResultID != value))
				{
					this.OnParentsResultIDChanging(value);
					this.SendPropertyChanging();
					this._ParentsResultID = value;
					this.SendPropertyChanged("ParentsResultID");
					this.OnParentsResultIDChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.JtmMAT")]
	public partial class JtmMAT : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Material_CD;
		
		private string _Material_JA;
		
		private string _Material_CH;
		
		private string _Material_EN;
		
		private System.Nullable<bool> _BefResin_FG;
		
		private System.Nullable<bool> _Exclude_FG;
		
		private string _UpdUser_CD;
		
		private System.DateTime _LastUpd_DT;
		
		private bool _Del_FG;
		
		private string _Change_kB;
		
    #region 拡張メソッドの定義
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaterial_CDChanging(string value);
    partial void OnMaterial_CDChanged();
    partial void OnMaterial_JAChanging(string value);
    partial void OnMaterial_JAChanged();
    partial void OnMaterial_CHChanging(string value);
    partial void OnMaterial_CHChanged();
    partial void OnMaterial_ENChanging(string value);
    partial void OnMaterial_ENChanged();
    partial void OnBefResin_FGChanging(System.Nullable<bool> value);
    partial void OnBefResin_FGChanged();
    partial void OnExclude_FGChanging(System.Nullable<bool> value);
    partial void OnExclude_FGChanged();
    partial void OnUpdUser_CDChanging(string value);
    partial void OnUpdUser_CDChanged();
    partial void OnLastUpd_DTChanging(System.DateTime value);
    partial void OnLastUpd_DTChanged();
    partial void OnDel_FGChanging(bool value);
    partial void OnDel_FGChanged();
    partial void OnChange_kBChanging(string value);
    partial void OnChange_kBChanged();
    #endregion
		
		public JtmMAT()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Material_CD", DbType="Char(24) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Material_CD
		{
			get
			{
				return this._Material_CD;
			}
			set
			{
				if ((this._Material_CD != value))
				{
					this.OnMaterial_CDChanging(value);
					this.SendPropertyChanging();
					this._Material_CD = value;
					this.SendPropertyChanged("Material_CD");
					this.OnMaterial_CDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Material_JA", DbType="NVarChar(64)")]
		public string Material_JA
		{
			get
			{
				return this._Material_JA;
			}
			set
			{
				if ((this._Material_JA != value))
				{
					this.OnMaterial_JAChanging(value);
					this.SendPropertyChanging();
					this._Material_JA = value;
					this.SendPropertyChanged("Material_JA");
					this.OnMaterial_JAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Material_CH", DbType="NVarChar(64)")]
		public string Material_CH
		{
			get
			{
				return this._Material_CH;
			}
			set
			{
				if ((this._Material_CH != value))
				{
					this.OnMaterial_CHChanging(value);
					this.SendPropertyChanging();
					this._Material_CH = value;
					this.SendPropertyChanged("Material_CH");
					this.OnMaterial_CHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Material_EN", DbType="NVarChar(64)")]
		public string Material_EN
		{
			get
			{
				return this._Material_EN;
			}
			set
			{
				if ((this._Material_EN != value))
				{
					this.OnMaterial_ENChanging(value);
					this.SendPropertyChanging();
					this._Material_EN = value;
					this.SendPropertyChanged("Material_EN");
					this.OnMaterial_ENChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BefResin_FG", DbType="Bit")]
		public System.Nullable<bool> BefResin_FG
		{
			get
			{
				return this._BefResin_FG;
			}
			set
			{
				if ((this._BefResin_FG != value))
				{
					this.OnBefResin_FGChanging(value);
					this.SendPropertyChanging();
					this._BefResin_FG = value;
					this.SendPropertyChanged("BefResin_FG");
					this.OnBefResin_FGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Exclude_FG", DbType="Bit")]
		public System.Nullable<bool> Exclude_FG
		{
			get
			{
				return this._Exclude_FG;
			}
			set
			{
				if ((this._Exclude_FG != value))
				{
					this.OnExclude_FGChanging(value);
					this.SendPropertyChanging();
					this._Exclude_FG = value;
					this.SendPropertyChanged("Exclude_FG");
					this.OnExclude_FGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdUser_CD", DbType="Char(8) NOT NULL", CanBeNull=false)]
		public string UpdUser_CD
		{
			get
			{
				return this._UpdUser_CD;
			}
			set
			{
				if ((this._UpdUser_CD != value))
				{
					this.OnUpdUser_CDChanging(value);
					this.SendPropertyChanging();
					this._UpdUser_CD = value;
					this.SendPropertyChanged("UpdUser_CD");
					this.OnUpdUser_CDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastUpd_DT", DbType="DateTime NOT NULL")]
		public System.DateTime LastUpd_DT
		{
			get
			{
				return this._LastUpd_DT;
			}
			set
			{
				if ((this._LastUpd_DT != value))
				{
					this.OnLastUpd_DTChanging(value);
					this.SendPropertyChanging();
					this._LastUpd_DT = value;
					this.SendPropertyChanged("LastUpd_DT");
					this.OnLastUpd_DTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Del_FG", DbType="Bit NOT NULL")]
		public bool Del_FG
		{
			get
			{
				return this._Del_FG;
			}
			set
			{
				if ((this._Del_FG != value))
				{
					this.OnDel_FGChanging(value);
					this.SendPropertyChanging();
					this._Del_FG = value;
					this.SendPropertyChanged("Del_FG");
					this.OnDel_FGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Change_kB", DbType="Char(24)")]
		public string Change_kB
		{
			get
			{
				return this._Change_kB;
			}
			set
			{
				if ((this._Change_kB != value))
				{
					this.OnChange_kBChanging(value);
					this.SendPropertyChanging();
					this._Change_kB = value;
					this.SendPropertyChanged("Change_kB");
					this.OnChange_kBChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.JtmMATCONV")]
	public partial class JtmMATCONV : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _ResinMat_CD;
		
		private string _RootsMat_CD;
		
		private bool _Del_FG;
		
		private string _UpdUser_CD;
		
		private System.DateTime _LastUpd_DT;
		
    #region 拡張メソッドの定義
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnResinMat_CDChanging(string value);
    partial void OnResinMat_CDChanged();
    partial void OnRootsMat_CDChanging(string value);
    partial void OnRootsMat_CDChanged();
    partial void OnDel_FGChanging(bool value);
    partial void OnDel_FGChanged();
    partial void OnUpdUser_CDChanging(string value);
    partial void OnUpdUser_CDChanged();
    partial void OnLastUpd_DTChanging(System.DateTime value);
    partial void OnLastUpd_DTChanged();
    #endregion
		
		public JtmMATCONV()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ResinMat_CD", DbType="Char(24) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string ResinMat_CD
		{
			get
			{
				return this._ResinMat_CD;
			}
			set
			{
				if ((this._ResinMat_CD != value))
				{
					this.OnResinMat_CDChanging(value);
					this.SendPropertyChanging();
					this._ResinMat_CD = value;
					this.SendPropertyChanged("ResinMat_CD");
					this.OnResinMat_CDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RootsMat_CD", DbType="Char(24) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string RootsMat_CD
		{
			get
			{
				return this._RootsMat_CD;
			}
			set
			{
				if ((this._RootsMat_CD != value))
				{
					this.OnRootsMat_CDChanging(value);
					this.SendPropertyChanging();
					this._RootsMat_CD = value;
					this.SendPropertyChanged("RootsMat_CD");
					this.OnRootsMat_CDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Del_FG", DbType="Bit NOT NULL")]
		public bool Del_FG
		{
			get
			{
				return this._Del_FG;
			}
			set
			{
				if ((this._Del_FG != value))
				{
					this.OnDel_FGChanging(value);
					this.SendPropertyChanging();
					this._Del_FG = value;
					this.SendPropertyChanged("Del_FG");
					this.OnDel_FGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdUser_CD", DbType="Char(8) NOT NULL", CanBeNull=false)]
		public string UpdUser_CD
		{
			get
			{
				return this._UpdUser_CD;
			}
			set
			{
				if ((this._UpdUser_CD != value))
				{
					this.OnUpdUser_CDChanging(value);
					this.SendPropertyChanging();
					this._UpdUser_CD = value;
					this.SendPropertyChanged("UpdUser_CD");
					this.OnUpdUser_CDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastUpd_DT", DbType="DateTime NOT NULL")]
		public System.DateTime LastUpd_DT
		{
			get
			{
				return this._LastUpd_DT;
			}
			set
			{
				if ((this._LastUpd_DT != value))
				{
					this.OnLastUpd_DTChanging(value);
					this.SendPropertyChanging();
					this._LastUpd_DT = value;
					this.SendPropertyChanged("LastUpd_DT");
					this.OnLastUpd_DTChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
